import type { IconSchema, IconLibrary } from './schema'

const BASE = 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons'

const blackIcons: IconSchema[] = [
    {
        id: 'active-search',
        label: 'Active Search',
        category: 'search',
        color: 'black',
        tags: ['search', 'find', 'lookup', 'discovery', 'research', 'query'],
        pngUrl: `${BASE}/Active+Search.png`,
    },
    {
        id: 'adaptation-ai',
        label: 'Adaptation AI',
        category: 'ai',
        color: 'black',
        tags: ['ai', 'artificial intelligence', 'machine learning', 'adaptation', 'smart', 'automation'],
        pngUrl: `${BASE}/Adaptation+Ai.png`,
    },
    {
        id: 'app-development',
        label: 'App Development',
        category: 'technology',
        color: 'black',
        tags: ['app', 'development', 'mobile', 'software', 'build', 'product', 'engineering'],
        pngUrl: `${BASE}/App+development.png`,
    },
    {
        id: 'calendar',
        label: 'Calendar',
        category: 'productivity',
        color: 'black',
        tags: ['calendar', 'schedule', 'planning', 'time', 'date', 'events', 'meeting'],
        pngUrl: `${BASE}/Calendar.png`,
    },
    {
        id: 'campaign-marketing',
        label: 'Campaign Marketing',
        category: 'marketing',
        color: 'black',
        tags: ['campaign', 'marketing', 'advertising', 'promotion', 'outreach', 'brand'],
        pngUrl: `${BASE}/Campaign+marketing.png`,
    },
    {
        id: 'chat',
        label: 'Chat',
        category: 'communication',
        color: 'black',
        tags: ['chat', 'message', 'conversation', 'communication', 'support', 'dialogue'],
        pngUrl: `${BASE}/Chat.png`,
    },
    {
        id: 'cloud-sync',
        label: 'Cloud Sync',
        category: 'technology',
        color: 'black',
        tags: ['cloud', 'sync', 'backup', 'storage', 'integration', 'data', 'upload'],
        pngUrl: `${BASE}/Cloud+sync.png`,
    },
    {
        id: 'coding',
        label: 'Coding',
        category: 'technology',
        color: 'black',
        tags: ['coding', 'programming', 'development', 'engineering', 'software', 'code'],
        pngUrl: `${BASE}/Coding.png`,
    },
    {
        id: 'company-growth',
        label: 'Company Growth',
        category: 'business',
        color: 'black',
        tags: ['growth', 'company', 'expansion', 'scale', 'business', 'success', 'progress'],
        pngUrl: `${BASE}/Company+-growth.png`,
    },
    {
        id: 'creative-content',
        label: 'Creative Content',
        category: 'marketing',
        color: 'black',
        tags: ['creative', 'content', 'design', 'media', 'storytelling', 'writing', 'copy'],
        pngUrl: `${BASE}/Creative+content.png`,
    },
    {
        id: 'customer-support',
        label: 'Customer Support',
        category: 'support',
        color: 'black',
        tags: ['customer', 'support', 'service', 'help', 'assistance', 'care', 'helpdesk'],
        pngUrl: `${BASE}/Customer+support.png`,
    },
    {
        id: 'data-analytics',
        label: 'Data Analytics',
        category: 'analytics',
        color: 'black',
        tags: ['data', 'analytics', 'insights', 'metrics', 'reporting', 'analysis', 'dashboard'],
        pngUrl: `${BASE}/data+analytics.png`,
    },
    {
        id: 'data-download',
        label: 'Data Download',
        category: 'analytics',
        color: 'black',
        tags: ['data', 'download', 'export', 'transfer', 'extract', 'retrieve'],
        pngUrl: `${BASE}/Data+Download.png`,
    },
    {
        id: 'deploy',
        label: 'Deploy',
        category: 'technology',
        color: 'black',
        tags: ['deploy', 'launch', 'release', 'ship', 'publish', 'go-live', 'production'],
        pngUrl: `${BASE}/Deploy.png`,
    },
    {
        id: 'email-marketing-option2',
        label: 'Email Marketing Option 2',
        category: 'marketing',
        color: 'black',
        tags: ['email', 'marketing', 'newsletter', 'outreach', 'campaign', 'inbox'],
        pngUrl: `${BASE}/Email+Marketing_Option2.png`,
    },
    {
        id: 'email-marketing-option1',
        label: 'Email Marketing Option 1',
        category: 'marketing',
        color: 'black',
        tags: ['email', 'marketing', 'newsletter', 'outreach', 'campaign', 'inbox'],
        pngUrl: `${BASE}/Email+Marketing-+Option+01.png`,
    },
    {
        id: 'global-campaign',
        label: 'Global Campaign',
        category: 'marketing',
        color: 'black',
        tags: ['global', 'campaign', 'international', 'worldwide', 'reach', 'market', 'expansion'],
        pngUrl: `${BASE}/Global+compaign.png`,
    },
    {
        id: 'increase-performance',
        label: 'Increase Performance',
        category: 'analytics',
        color: 'black',
        tags: ['performance', 'increase', 'improve', 'optimize', 'boost', 'efficiency', 'results'],
        pngUrl: `${BASE}/Increase+performance.png`,
    },
    {
        id: 'keyword-search',
        label: 'Keyword Search',
        category: 'search',
        color: 'black',
        tags: ['keyword', 'search', 'seo', 'query', 'terms', 'discovery', 'targeting'],
        pngUrl: `${BASE}/Keyword+search.png`,
    },
    {
        id: 'leadership-change',
        label: 'Leadership Change',
        category: 'business',
        color: 'black',
        tags: ['leadership', 'change', 'management', 'transition', 'strategy', 'direction', 'vision'],
        pngUrl: `${BASE}/Leadership+-Change.png`,
    },
    {
        id: 'linking',
        label: 'Linking',
        category: 'technology',
        color: 'black',
        tags: ['link', 'connect', 'integration', 'url', 'backlink', 'reference', 'chain'],
        pngUrl: `${BASE}/Linking.png`,
    },
    {
        id: 'marketing-automation',
        label: 'Marketing Automation',
        category: 'marketing',
        color: 'black',
        tags: ['automation', 'marketing', 'workflow', 'trigger', 'sequence', 'nurture', 'pipeline'],
        pngUrl: `${BASE}/Marketing+automation.png`,
    },
    {
        id: 'network-option1',
        label: 'Network Option 1',
        category: 'technology',
        color: 'black',
        tags: ['network', 'connection', 'infrastructure', 'nodes', 'web', 'ecosystem', 'platform'],
        pngUrl: `${BASE}/Network_Option+01.png`,
    },
    {
        id: 'network-option2',
        label: 'Network Option 2',
        category: 'technology',
        color: 'black',
        tags: ['network', 'connection', 'infrastructure', 'nodes', 'web', 'ecosystem', 'platform'],
        pngUrl: `${BASE}/Network_Option+02.png`,
    },
    {
        id: 'online-support',
        label: 'Online Support',
        category: 'support',
        color: 'black',
        tags: ['online', 'support', 'helpdesk', 'service', 'chat', 'remote', 'assistance'],
        pngUrl: `${BASE}/Online+Support.png`,
    },
    {
        id: 'partnership',
        label: 'Partnership',
        category: 'business',
        color: 'black',
        tags: ['partnership', 'collaboration', 'alliance', 'joint', 'together', 'team', 'relations'],
        pngUrl: `${BASE}/Partnership.png`,
    },
    {
        id: 'responsive',
        label: 'Responsive',
        category: 'technology',
        color: 'black',
        tags: ['responsive', 'mobile', 'adaptive', 'design', 'device', 'screen', 'layout'],
        pngUrl: `${BASE}/Responsive.png`,
    },
    {
        id: 'revenue',
        label: 'Revenue',
        category: 'business',
        color: 'black',
        tags: ['revenue', 'income', 'sales', 'profit', 'money', 'earnings', 'roi'],
        pngUrl: `${BASE}/Revenue.png`,
    },
    {
        id: 'seo-location',
        label: 'SEO Location',
        category: 'seo',
        color: 'black',
        tags: ['seo', 'location', 'local', 'geo', 'map', 'targeting', 'search'],
        pngUrl: `${BASE}/SEO+location.png`,
    },
    {
        id: 'seo-plugin-option1',
        label: 'SEO Plugin Option 1',
        category: 'seo',
        color: 'black',
        tags: ['seo', 'plugin', 'tool', 'optimization', 'search', 'ranking', 'engine'],
        pngUrl: `${BASE}/SEO+plugin_Option+01.png`,
    },
    {
        id: 'seo-option1',
        label: 'SEO Option 1',
        category: 'seo',
        color: 'black',
        tags: ['seo', 'optimization', 'search', 'ranking', 'organic', 'visibility', 'engine'],
        pngUrl: `${BASE}/SEO_Option+01.png`,
    },
    {
        id: 'sitemap',
        label: 'Sitemap',
        category: 'seo',
        color: 'black',
        tags: ['sitemap', 'structure', 'navigation', 'architecture', 'pages', 'crawl', 'index'],
        pngUrl: `${BASE}/Sitemap.png`,
    },
    {
        id: 'social-network',
        label: 'Social Network',
        category: 'marketing',
        color: 'black',
        tags: ['social', 'network', 'media', 'community', 'platform', 'engagement', 'followers'],
        pngUrl: `${BASE}/Social+network.png`,
    },
    {
        id: 'target-audience',
        label: 'Target Audience',
        category: 'marketing',
        color: 'black',
        tags: ['target', 'audience', 'persona', 'segment', 'demographic', 'reach', 'focus'],
        pngUrl: `${BASE}/Target+audiance+.png`,
    },
    {
        id: 'team-building',
        label: 'Team Building',
        category: 'business',
        color: 'black',
        tags: ['team', 'building', 'people', 'culture', 'collaboration', 'hiring', 'talent'],
        pngUrl: `${BASE}/Team+building.png`,
    },
    {
        id: 'thinking-process',
        label: 'Thinking Process',
        category: 'business',
        color: 'black',
        tags: ['thinking', 'process', 'strategy', 'planning', 'ideation', 'brainstorm', 'decision'],
        pngUrl: `${BASE}/Thinking+process.png`,
    },
    {
        id: 'time-management',
        label: 'Time Management',
        category: 'productivity',
        color: 'black',
        tags: ['time', 'management', 'efficiency', 'planning', 'deadline', 'schedule', 'productivity'],
        pngUrl: `${BASE}/Time+management.png`,
    },
    {
        id: 'traffic',
        label: 'Traffic',
        category: 'analytics',
        color: 'black',
        tags: ['traffic', 'visits', 'sessions', 'users', 'web', 'inbound', 'acquisition'],
        pngUrl: `${BASE}/Traffic.png`,
    },
    {
        id: 'user-experience',
        label: 'User Experience',
        category: 'technology',
        color: 'black',
        tags: ['ux', 'user experience', 'design', 'usability', 'interface', 'journey', 'product'],
        pngUrl: `${BASE}/User+experience+.png`,
    },
    {
        id: 'user-interaction',
        label: 'User Interaction',
        category: 'technology',
        color: 'black',
        tags: ['user', 'interaction', 'engagement', 'click', 'behavior', 'interface', 'action'],
        pngUrl: `${BASE}/User+interaction.png`,
    },
    {
        id: 'video-marketing',
        label: 'Video Marketing',
        category: 'marketing',
        color: 'black',
        tags: ['video', 'marketing', 'content', 'media', 'youtube', 'visual', 'campaign'],
        pngUrl: `${BASE}/Video+marketing.png`,
    },
    {
        id: 'web-optimisation',
        label: 'Web Optimisation',
        category: 'technology',
        color: 'black',
        tags: ['web', 'optimisation', 'performance', 'speed', 'core web vitals', 'loading', 'site'],
        pngUrl: `${BASE}/Web+optimisation.png`,
    },
    {
        id: 'laptop-settings',
        label: 'Laptop Settings',
        category: 'technology',
        color: 'black',
        tags: ['laptop', 'settings', 'configuration', 'device', 'setup', 'system', 'it'],
        pngUrl: `${BASE}/Laptop+settings.png`,
    },
    {
        id: 'search-optimisation-seo',
        label: 'Search Optimisation SEO',
        category: 'seo',
        color: 'black',
        tags: ['seo', 'search', 'optimisation', 'ranking', 'organic', 'visibility', 'engine'],
        pngUrl: `${BASE}/Search+optimisation+-+SEO.png`,
    },
]

const whiteIcons: IconSchema[] = [
    {
        id: 'active-search-white',
        label: 'Active Search',
        category: 'search',
        color: 'white',
        tags: ['search', 'find', 'lookup', 'discovery', 'research', 'query'],
        pngUrl: `${BASE}/white/Active+Search.png`,
    },
    {
        id: 'adaptation-ai-white',
        label: 'Adaptation AI',
        category: 'ai',
        color: 'white',
        tags: ['ai', 'artificial intelligence', 'machine learning', 'adaptation', 'smart', 'automation'],
        pngUrl: `${BASE}/white/Adaptation+Ai.png`,
    },
    {
        id: 'app-development-white',
        label: 'App Development',
        category: 'technology',
        color: 'white',
        tags: ['app', 'development', 'mobile', 'software', 'build', 'product', 'engineering'],
        pngUrl: `${BASE}/white/App+development.png`,
    },
    {
        id: 'calendar-white',
        label: 'Calendar',
        category: 'productivity',
        color: 'white',
        tags: ['calendar', 'schedule', 'planning', 'time', 'date', 'events', 'meeting'],
        pngUrl: `${BASE}/white/Calendar.png`,
    },
    {
        id: 'campaign-marketing-white',
        label: 'Campaign Marketing',
        category: 'marketing',
        color: 'white',
        tags: ['campaign', 'marketing', 'advertising', 'promotion', 'outreach', 'brand'],
        pngUrl: `${BASE}/white/Campaign+marketing.png`,
    },
    {
        id: 'chat-white',
        label: 'Chat',
        category: 'communication',
        color: 'white',
        tags: ['chat', 'message', 'conversation', 'communication', 'support', 'dialogue'],
        pngUrl: `${BASE}/white/Chat.png`,
    },
    {
        id: 'cloud-sync-white',
        label: 'Cloud Sync',
        category: 'technology',
        color: 'white',
        tags: ['cloud', 'sync', 'backup', 'storage', 'integration', 'data', 'upload'],
        pngUrl: `${BASE}/white/Cloud+sync.png`,
    },
    {
        id: 'coding-white',
        label: 'Coding',
        category: 'technology',
        color: 'white',
        tags: ['coding', 'programming', 'development', 'engineering', 'software', 'code'],
        pngUrl: `${BASE}/white/Coding.png`,
    },
    {
        id: 'company-growth-white',
        label: 'Company Growth',
        category: 'business',
        color: 'white',
        tags: ['growth', 'company', 'expansion', 'scale', 'business', 'success', 'progress'],
        pngUrl: `${BASE}/white/Company+-growth.png`,
    },
    {
        id: 'creative-content-white',
        label: 'Creative Content',
        category: 'marketing',
        color: 'white',
        tags: ['creative', 'content', 'design', 'media', 'storytelling', 'writing', 'copy'],
        pngUrl: `${BASE}/white/Creative+content.png`,
    },
    {
        id: 'customer-support-white',
        label: 'Customer Support',
        category: 'support',
        color: 'white',
        tags: ['customer', 'support', 'service', 'help', 'assistance', 'care', 'helpdesk'],
        pngUrl: `${BASE}/white/Customer+support.png`,
    },
    {
        id: 'data-analytics-white',
        label: 'Data Analytics',
        category: 'analytics',
        color: 'white',
        tags: ['data', 'analytics', 'insights', 'metrics', 'reporting', 'analysis', 'dashboard'],
        pngUrl: `${BASE}/white/data+analytics.png`,
    },
    {
        id: 'data-download-white',
        label: 'Data Download',
        category: 'analytics',
        color: 'white',
        tags: ['data', 'download', 'export', 'transfer', 'extract', 'retrieve'],
        pngUrl: `${BASE}/white/Data+Download.png`,
    },
    {
        id: 'deploy-white',
        label: 'Deploy',
        category: 'technology',
        color: 'white',
        tags: ['deploy', 'launch', 'release', 'ship', 'publish', 'go-live', 'production'],
        pngUrl: `${BASE}/white/Deploy.png`,
    },
    {
        id: 'email-marketing-option2-white',
        label: 'Email Marketing Option 2',
        category: 'marketing',
        color: 'white',
        tags: ['email', 'marketing', 'newsletter', 'outreach', 'campaign', 'inbox'],
        pngUrl: `${BASE}/white/Email+Marketing_Option2.png`,
    },
    {
        id: 'email-marketing-option1-white',
        label: 'Email Marketing Option 1',
        category: 'marketing',
        color: 'white',
        tags: ['email', 'marketing', 'newsletter', 'outreach', 'campaign', 'inbox'],
        pngUrl: `${BASE}/white/Email+Marketing-+Option+01.png`,
    },
    {
        id: 'global-campaign-white',
        label: 'Global Campaign',
        category: 'marketing',
        color: 'white',
        tags: ['global', 'campaign', 'international', 'worldwide', 'reach', 'market', 'expansion'],
        pngUrl: `${BASE}/white/Global+compaign.png`,
    },
    {
        id: 'increase-performance-white',
        label: 'Increase Performance',
        category: 'analytics',
        color: 'white',
        tags: ['performance', 'increase', 'improve', 'optimize', 'boost', 'efficiency', 'results'],
        pngUrl: `${BASE}/white/Increase+performance.png`,
    },
    {
        id: 'keyword-search-white',
        label: 'Keyword Search',
        category: 'search',
        color: 'white',
        tags: ['keyword', 'search', 'seo', 'query', 'terms', 'discovery', 'targeting'],
        pngUrl: `${BASE}/white/Keyword+search.png`,
    },
    {
        id: 'leadership-change-white',
        label: 'Leadership Change',
        category: 'business',
        color: 'white',
        tags: ['leadership', 'change', 'management', 'transition', 'strategy', 'direction', 'vision'],
        pngUrl: `${BASE}/white/Leadership+-Change.png`,
    },
    {
        id: 'linking-white',
        label: 'Linking',
        category: 'technology',
        color: 'white',
        tags: ['link', 'connect', 'integration', 'url', 'backlink', 'reference', 'chain'],
        pngUrl: `${BASE}/white/Linking.png`,
    },
    {
        id: 'marketing-automation-white',
        label: 'Marketing Automation',
        category: 'marketing',
        color: 'white',
        tags: ['automation', 'marketing', 'workflow', 'trigger', 'sequence', 'nurture', 'pipeline'],
        pngUrl: `${BASE}/white/Marketing+automation.png`,
    },
    {
        id: 'network-option1-white',
        label: 'Network Option 1',
        category: 'technology',
        color: 'white',
        tags: ['network', 'connection', 'infrastructure', 'nodes', 'web', 'ecosystem', 'platform'],
        pngUrl: `${BASE}/white/Network_Option+01.png`,
    },
    {
        id: 'network-option2-white',
        label: 'Network Option 2',
        category: 'technology',
        color: 'white',
        tags: ['network', 'connection', 'infrastructure', 'nodes', 'web', 'ecosystem', 'platform'],
        pngUrl: `${BASE}/white/Network_Option+02.png`,
    },
    {
        id: 'online-support-white',
        label: 'Online Support',
        category: 'support',
        color: 'white',
        tags: ['online', 'support', 'helpdesk', 'service', 'chat', 'remote', 'assistance'],
        pngUrl: `${BASE}/white/Online+Support.png`,
    },
    {
        id: 'partnership-white',
        label: 'Partnership',
        category: 'business',
        color: 'white',
        tags: ['partnership', 'collaboration', 'alliance', 'joint', 'together', 'team', 'relations'],
        pngUrl: `${BASE}/white/Partnership.png`,
    },
    {
        id: 'responsive-white',
        label: 'Responsive',
        category: 'technology',
        color: 'white',
        tags: ['responsive', 'mobile', 'adaptive', 'design', 'device', 'screen', 'layout'],
        pngUrl: `${BASE}/white/Responsive.png`,
    },
    {
        id: 'revenue-white',
        label: 'Revenue',
        category: 'business',
        color: 'white',
        tags: ['revenue', 'income', 'sales', 'profit', 'money', 'earnings', 'roi'],
        pngUrl: `${BASE}/white/Revenue.png`,
    },
    {
        id: 'seo-location-white',
        label: 'SEO Location',
        category: 'seo',
        color: 'white',
        tags: ['seo', 'location', 'local', 'geo', 'map', 'targeting', 'search'],
        pngUrl: `${BASE}/white/SEO+location.png`,
    },
    {
        id: 'seo-plugin-option1-white',
        label: 'SEO Plugin Option 1',
        category: 'seo',
        color: 'white',
        tags: ['seo', 'plugin', 'tool', 'optimization', 'search', 'ranking', 'engine'],
        pngUrl: `${BASE}/white/SEO+plugin_Option+01.png`,
    },
    {
        id: 'seo-option1-white',
        label: 'SEO Option 1',
        category: 'seo',
        color: 'white',
        tags: ['seo', 'optimization', 'search', 'ranking', 'organic', 'visibility', 'engine'],
        pngUrl: `${BASE}/white/SEO_Option+01.png`,
    },
    {
        id: 'sitemap-white',
        label: 'Sitemap',
        category: 'seo',
        color: 'white',
        tags: ['sitemap', 'structure', 'navigation', 'architecture', 'pages', 'crawl', 'index'],
        pngUrl: `${BASE}/white/Sitemap.png`,
    },
    {
        id: 'social-network-white',
        label: 'Social Network',
        category: 'marketing',
        color: 'white',
        tags: ['social', 'network', 'media', 'community', 'platform', 'engagement', 'followers'],
        pngUrl: `${BASE}/white/Social+network.png`,
    },
    {
        id: 'target-audience-white',
        label: 'Target Audience',
        category: 'marketing',
        color: 'white',
        tags: ['target', 'audience', 'persona', 'segment', 'demographic', 'reach', 'focus'],
        pngUrl: `${BASE}/white/Target+audiance+.png`,
    },
    {
        id: 'team-building-white',
        label: 'Team Building',
        category: 'business',
        color: 'white',
        tags: ['team', 'building', 'people', 'culture', 'collaboration', 'hiring', 'talent'],
        pngUrl: `${BASE}/white/Team+building.png`,
    },
    {
        id: 'thinking-process-white',
        label: 'Thinking Process',
        category: 'business',
        color: 'white',
        tags: ['thinking', 'process', 'strategy', 'planning', 'ideation', 'brainstorm', 'decision'],
        pngUrl: `${BASE}/white/Thinking+process.png`,
    },
    {
        id: 'time-management-white',
        label: 'Time Management',
        category: 'productivity',
        color: 'white',
        tags: ['time', 'management', 'efficiency', 'planning', 'deadline', 'schedule', 'productivity'],
        pngUrl: `${BASE}/white/Time+management.png`,
    },
    {
        id: 'traffic-white',
        label: 'Traffic',
        category: 'analytics',
        color: 'white',
        tags: ['traffic', 'visits', 'sessions', 'users', 'web', 'inbound', 'acquisition'],
        pngUrl: `${BASE}/white/Traffic.png`,
    },
    {
        id: 'user-experience-white',
        label: 'User Experience',
        category: 'technology',
        color: 'white',
        tags: ['ux', 'user experience', 'design', 'usability', 'interface', 'journey', 'product'],
        pngUrl: `${BASE}/white/User+experience+.png`,
    },
    {
        id: 'user-interaction-white',
        label: 'User Interaction',
        category: 'technology',
        color: 'white',
        tags: ['user', 'interaction', 'engagement', 'click', 'behavior', 'interface', 'action'],
        pngUrl: `${BASE}/white/User+interaction.png`,
    },
    {
        id: 'video-marketing-white',
        label: 'Video Marketing',
        category: 'marketing',
        color: 'white',
        tags: ['video', 'marketing', 'content', 'media', 'youtube', 'visual', 'campaign'],
        pngUrl: `${BASE}/white/Video+marketing.png`,
    },
    {
        id: 'web-optimisation-white',
        label: 'Web Optimisation',
        category: 'technology',
        color: 'white',
        tags: ['web', 'optimisation', 'performance', 'speed', 'core web vitals', 'loading', 'site'],
        pngUrl: `${BASE}/white/Web+optimisation.png`,
    },
    {
        id: 'laptop-settings-white',
        label: 'Laptop Settings',
        category: 'technology',
        color: 'white',
        tags: ['laptop', 'settings', 'configuration', 'device', 'setup', 'system', 'it'],
        pngUrl: `${BASE}/white/Laptop+settings.png`,
    },
    {
        id: 'search-optimisation-seo-white',
        label: 'Search Optimisation SEO',
        category: 'seo',
        color: 'white',
        tags: ['seo', 'search', 'optimisation', 'ranking', 'organic', 'visibility', 'engine'],
        pngUrl: `${BASE}/white/Search+optimisation+-+SEO.png`,
    },
]

export const iconLibrary: IconLibrary = {
    version: '1.0',
    baseUrl: BASE,
    icons: [...blackIcons, ...whiteIcons],
}
