import type { IconSchema, IconLibrary } from './schema'

const BASE = 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons'

const blackIcons: IconSchema[] = [
    {
        id: 'ai-adaptation-generic',
        label: 'AI Adaptation',
        category: 'generic',
        color: 'black',
        tags: ['ai', 'artificial intelligence', 'adaptation', 'machine learning', 'smart', 'automation'],
        pngUrl: `${BASE}/black/generic/ai+adaptation.png`,
    },
    {
        id: 'app-development-generic',
        label: 'App Development',
        category: 'generic',
        color: 'black',
        tags: ['app', 'development', 'mobile', 'software', 'build', 'product', 'engineering'],
        pngUrl: `${BASE}/black/generic/app+development.png`,
    },
    {
        id: 'campaign-marketing-generic',
        label: 'Campaign Marketing',
        category: 'generic',
        color: 'black',
        tags: ['campaign', 'marketing', 'advertising', 'promotion', 'outreach', 'brand'],
        pngUrl: `${BASE}/black/generic/campaign+marketing.png`,
    },
    {
        id: 'company-growth-generic',
        label: 'Company Growth',
        category: 'generic',
        color: 'black',
        tags: ['growth', 'company', 'expansion', 'scale', 'business', 'success', 'progress'],
        pngUrl: `${BASE}/black/generic/Company+growth.png`,
    },
    {
        id: 'creative-content-generic',
        label: 'Creative Content',
        category: 'generic',
        color: 'black',
        tags: ['creative', 'content', 'design', 'media', 'storytelling', 'writing', 'copy'],
        pngUrl: `${BASE}/black/generic/Creative+content.png`,
    },
    {
        id: 'creative-process-generic',
        label: 'Creative Process',
        category: 'generic',
        color: 'black',
        tags: ['creative', 'process', 'ideation', 'brainstorm', 'design thinking', 'innovation', 'workflow'],
        pngUrl: `${BASE}/black/generic/creative+process.png`,
    },
    {
        id: 'deploy-generic',
        label: 'Deploy',
        category: 'generic',
        color: 'black',
        tags: ['deploy', 'launch', 'release', 'ship', 'publish', 'go-live', 'production'],
        pngUrl: `${BASE}/black/generic/Deploy.png`,
    },
    {
        id: 'laptop-settings-generic',
        label: 'Laptop Settings',
        category: 'generic',
        color: 'black',
        tags: ['laptop', 'settings', 'configuration', 'device', 'setup', 'system', 'it'],
        pngUrl: `${BASE}/black/generic/laptop+settings.png`,
    },
    {
        id: 'leadership-change-generic',
        label: 'Leadership Change',
        category: 'generic',
        color: 'black',
        tags: ['leadership', 'change', 'management', 'transition', 'strategy', 'direction', 'vision'],
        pngUrl: `${BASE}/black/generic/Leadership+Change.png`,
    },
    {
        id: 'partnership-generic',
        label: 'Partnership',
        category: 'generic',
        color: 'black',
        tags: ['partnership', 'collaboration', 'alliance', 'joint', 'together', 'team', 'relations'],
        pngUrl: `${BASE}/black/generic/partnership.png`,
    },
    {
        id: 'revenue-generic',
        label: 'Revenue',
        category: 'generic',
        color: 'black',
        tags: ['revenue', 'income', 'sales', 'profit', 'money', 'earnings', 'roi'],
        pngUrl: `${BASE}/black/generic/Revenue.png`,
    },
    {
        id: 'user-experience-generic',
        label: 'User Experience',
        category: 'generic',
        color: 'black',
        tags: ['ux', 'user experience', 'design', 'usability', 'interface', 'journey', 'product'],
        pngUrl: `${BASE}/black/generic/user+experience.png`,
    },
    {
        id: 'user-interaction-generic',
        label: 'User Interaction',
        category: 'generic',
        color: 'black',
        tags: ['user', 'interaction', 'engagement', 'click', 'behavior', 'interface', 'action'],
        pngUrl: `${BASE}/black/generic/user+interaction.png`,
    },
    {
        id: 'customer-support-marketing',
        label: 'Customer Support',
        category: 'marketing',
        color: 'black',
        tags: ['customer', 'support', 'service', 'help', 'assistance', 'care', 'helpdesk'],
        pngUrl: `${BASE}/black/marketing/Customer+Support.png`,
    },
    {
        id: 'global-campaign-marketing',
        label: 'Global Campaign',
        category: 'marketing',
        color: 'black',
        tags: ['global', 'campaign', 'international', 'worldwide', 'reach', 'market', 'expansion'],
        pngUrl: `${BASE}/black/marketing/Global+Campaign.png`,
    },
    {
        id: 'keyword-search-marketing',
        label: 'Keyword Search',
        category: 'marketing',
        color: 'black',
        tags: ['keyword', 'search', 'seo', 'query', 'terms', 'discovery', 'targeting'],
        pngUrl: `${BASE}/black/marketing/Keyword+search.png`,
    },
    {
        id: 'marketing-automation-marketing',
        label: 'Marketing Automation',
        category: 'marketing',
        color: 'black',
        tags: ['automation', 'marketing', 'workflow', 'trigger', 'sequence', 'nurture', 'pipeline'],
        pngUrl: `${BASE}/black/marketing/Marketing+Automation.png`,
    },
    {
        id: 'network-option1-marketing',
        label: 'Network Option 1',
        category: 'marketing',
        color: 'black',
        tags: ['network', 'connection', 'infrastructure', 'nodes', 'web', 'ecosystem', 'platform'],
        pngUrl: `${BASE}/black/marketing/Network+Option+1.png`,
    },
    {
        id: 'network-option2-marketing',
        label: 'Network Option 2',
        category: 'marketing',
        color: 'black',
        tags: ['network', 'connection', 'infrastructure', 'nodes', 'web', 'ecosystem', 'platform'],
        pngUrl: `${BASE}/black/marketing/Network+Option+2.png`,
    },
    {
        id: 'responsive-marketing',
        label: 'Responsive',
        category: 'marketing',
        color: 'black',
        tags: ['responsive', 'mobile', 'adaptive', 'design', 'device', 'screen', 'layout'],
        pngUrl: `${BASE}/black/marketing/Responsive.png`,
    },
    {
        id: 'sitemap-marketing',
        label: 'Sitemap',
        category: 'marketing',
        color: 'black',
        tags: ['sitemap', 'structure', 'navigation', 'architecture', 'pages', 'crawl', 'index'],
        pngUrl: `${BASE}/black/marketing/Sitemap.png`,
    },
    {
        id: 'social-network-marketing',
        label: 'Social Network',
        category: 'marketing',
        color: 'black',
        tags: ['social', 'network', 'media', 'community', 'platform', 'engagement', 'followers'],
        pngUrl: `${BASE}/black/marketing/Social+Network.png`,
    },
    {
        id: 'team-building-marketing',
        label: 'Team Building',
        category: 'marketing',
        color: 'black',
        tags: ['team', 'building', 'people', 'culture', 'collaboration', 'hiring', 'talent'],
        pngUrl: `${BASE}/black/marketing/TeamBuilding.png`,
    },
    {
        id: 'active-search-seo',
        label: 'Active Search',
        category: 'seo',
        color: 'black',
        tags: ['search', 'find', 'lookup', 'discovery', 'research', 'query', 'seo'],
        pngUrl: `${BASE}/black/seo/Active+Search.png`,
    },
    {
        id: 'calendar-seo',
        label: 'Calendar',
        category: 'seo',
        color: 'black',
        tags: ['calendar', 'schedule', 'planning', 'time', 'date', 'events', 'meeting'],
        pngUrl: `${BASE}/black/seo/Calendar.png`,
    },
    {
        id: 'chat-seo',
        label: 'Chat',
        category: 'seo',
        color: 'black',
        tags: ['chat', 'message', 'conversation', 'communication', 'support', 'dialogue'],
        pngUrl: `${BASE}/black/seo/Chat.png`,
    },
    {
        id: 'cloud-sync-seo',
        label: 'Cloud Sync',
        category: 'seo',
        color: 'black',
        tags: ['cloud', 'sync', 'backup', 'storage', 'integration', 'data', 'upload'],
        pngUrl: `${BASE}/black/seo/Cloud+Sync.png`,
    },
    {
        id: 'coding-seo',
        label: 'Coding',
        category: 'seo',
        color: 'black',
        tags: ['coding', 'programming', 'development', 'engineering', 'software', 'code'],
        pngUrl: `${BASE}/black/seo/Coding.png`,
    },
    {
        id: 'data-analytics-seo',
        label: 'Data Analytics',
        category: 'seo',
        color: 'black',
        tags: ['data', 'analytics', 'insights', 'metrics', 'reporting', 'analysis', 'dashboard'],
        pngUrl: `${BASE}/black/seo/data+analystics.png`,
    },
    {
        id: 'data-download-seo',
        label: 'Data Download',
        category: 'seo',
        color: 'black',
        tags: ['data', 'download', 'export', 'transfer', 'extract', 'retrieve'],
        pngUrl: `${BASE}/black/seo/Data+Download.png`,
    },
    {
        id: 'email-marketing-option1-seo',
        label: 'Email Marketing Option 1',
        category: 'seo',
        color: 'black',
        tags: ['email', 'marketing', 'newsletter', 'outreach', 'campaign', 'inbox'],
        pngUrl: `${BASE}/black/seo/Email+Marketing+Option+1.png`,
    },
    {
        id: 'email-marketing-option2-seo',
        label: 'Email Marketing Option 2',
        category: 'seo',
        color: 'black',
        tags: ['email', 'marketing', 'newsletter', 'outreach', 'campaign', 'inbox'],
        pngUrl: `${BASE}/black/seo/Email+Marketing+Option+2.png`,
    },
    {
        id: 'increased-performance-seo',
        label: 'Increased Performance',
        category: 'seo',
        color: 'black',
        tags: ['performance', 'increase', 'improve', 'optimize', 'boost', 'efficiency', 'results'],
        pngUrl: `${BASE}/black/seo/Increased+Performance.png`,
    },
    {
        id: 'link-seo',
        label: 'Link',
        category: 'seo',
        color: 'black',
        tags: ['link', 'connect', 'integration', 'url', 'backlink', 'reference', 'chain'],
        pngUrl: `${BASE}/black/seo/Link.png`,
    },
    {
        id: 'online-support-seo',
        label: 'Online Support',
        category: 'seo',
        color: 'black',
        tags: ['online', 'support', 'helpdesk', 'service', 'chat', 'remote', 'assistance'],
        pngUrl: `${BASE}/black/seo/Online+Support.png`,
    },
    {
        id: 'seo-location-seo',
        label: 'SEO Location',
        category: 'seo',
        color: 'black',
        tags: ['seo', 'location', 'local', 'geo', 'map', 'targeting', 'search'],
        pngUrl: `${BASE}/black/seo/SEO+Location.png`,
    },
    {
        id: 'seo-option1-seo',
        label: 'SEO Option 1',
        category: 'seo',
        color: 'black',
        tags: ['seo', 'optimization', 'search', 'ranking', 'organic', 'visibility', 'engine'],
        pngUrl: `${BASE}/black/seo/SEO+Option+1.png`,
    },
    {
        id: 'seo-option2-seo',
        label: 'SEO Option 2',
        category: 'seo',
        color: 'black',
        tags: ['seo', 'optimization', 'search', 'ranking', 'organic', 'visibility', 'engine'],
        pngUrl: `${BASE}/black/seo/SEO+option+2.png`,
    },
    {
        id: 'seo-plugin-option2-seo',
        label: 'SEO Plugin Option 2',
        category: 'seo',
        color: 'black',
        tags: ['seo', 'plugin', 'tool', 'optimization', 'search', 'ranking', 'engine'],
        pngUrl: `${BASE}/black/seo/SEO+Plugin+option+2.png`,
    },
    {
        id: 'seo-plugin-seo',
        label: 'SEO Plugin',
        category: 'seo',
        color: 'black',
        tags: ['seo', 'plugin', 'tool', 'optimization', 'search', 'ranking', 'engine'],
        pngUrl: `${BASE}/black/seo/Seo+Plugin.png`,
    },
    {
        id: 'seo-seo',
        label: 'SEO',
        category: 'seo',
        color: 'black',
        tags: ['seo', 'search engine optimization', 'ranking', 'organic', 'visibility', 'traffic'],
        pngUrl: `${BASE}/black/seo/SEO.png`,
    },
    {
        id: 'target-seo',
        label: 'Target',
        category: 'seo',
        color: 'black',
        tags: ['target', 'audience', 'goal', 'focus', 'aim', 'precision', 'segment'],
        pngUrl: `${BASE}/black/seo/Target.png`,
    },
    {
        id: 'time-management-seo',
        label: 'Time Management',
        category: 'seo',
        color: 'black',
        tags: ['time', 'management', 'efficiency', 'planning', 'deadline', 'schedule', 'productivity'],
        pngUrl: `${BASE}/black/seo/Time+management.png`,
    },
    {
        id: 'traffic-seo',
        label: 'Traffic',
        category: 'seo',
        color: 'black',
        tags: ['traffic', 'visits', 'sessions', 'users', 'web', 'inbound', 'acquisition'],
        pngUrl: `${BASE}/black/seo/Traffic.png`,
    },
    {
        id: 'video-marketing-seo',
        label: 'Video Marketing',
        category: 'seo',
        color: 'black',
        tags: ['video', 'marketing', 'content', 'media', 'youtube', 'visual', 'campaign'],
        pngUrl: `${BASE}/black/seo/Video+marketing.png`,
    },
    {
        id: 'web-optimisation-seo',
        label: 'Web Optimisation',
        category: 'seo',
        color: 'black',
        tags: ['web', 'optimisation', 'performance', 'speed', 'core web vitals', 'loading', 'site'],
        pngUrl: `${BASE}/black/seo/Web+Optimisation.png`,
    },
]

const whiteIcons: IconSchema[] = [
    {
        id: 'ai-adaptation-generic-white',
        label: 'AI Adaptation',
        category: 'generic',
        color: 'white',
        tags: ['ai', 'artificial intelligence', 'adaptation', 'machine learning', 'smart', 'automation'],
        pngUrl: `${BASE}/white/generic/adaptation+-+white.png`,
    },
    {
        id: 'app-development-generic-white',
        label: 'App Development',
        category: 'generic',
        color: 'white',
        tags: ['app', 'development', 'mobile', 'software', 'build', 'product', 'engineering'],
        pngUrl: `${BASE}/white/generic/app+development+-+white.png`,
    },
    {
        id: 'campaign-marketing-generic-white',
        label: 'Campaign Marketing',
        category: 'generic',
        color: 'white',
        tags: ['campaign', 'marketing', 'advertising', 'promotion', 'outreach', 'brand'],
        pngUrl: `${BASE}/white/generic/campaign+marketing+-+white.png`,
    },
    {
        id: 'company-growth-generic-white',
        label: 'Company Growth',
        category: 'generic',
        color: 'white',
        tags: ['growth', 'company', 'expansion', 'scale', 'business', 'success', 'progress'],
        pngUrl: `${BASE}/white/generic/Company+growth+white.png`,
    },
    {
        id: 'creative-content-generic-white',
        label: 'Creative Content',
        category: 'generic',
        color: 'white',
        tags: ['creative', 'content', 'design', 'media', 'storytelling', 'writing', 'copy'],
        pngUrl: `${BASE}/white/generic/creative+content-white.png`,
    },
    {
        id: 'thinking-process-generic-white',
        label: 'Thinking Process',
        category: 'generic',
        color: 'white',
        tags: ['thinking', 'process', 'strategy', 'planning', 'ideation', 'brainstorm', 'decision'],
        pngUrl: `${BASE}/white/generic/thinking+process.png`,
    },
    {
        id: 'deploy-generic-white',
        label: 'Deploy',
        category: 'generic',
        color: 'white',
        tags: ['deploy', 'launch', 'release', 'ship', 'publish', 'go-live', 'production'],
        pngUrl: `${BASE}/white/generic/deploy-white.png`,
    },
    {
        id: 'laptop-settings-generic-white',
        label: 'Laptop Settings',
        category: 'generic',
        color: 'white',
        tags: ['laptop', 'settings', 'configuration', 'device', 'setup', 'system', 'it'],
        pngUrl: `${BASE}/white/generic/laptop+settings-white.png`,
    },
    {
        id: 'leadership-change-generic-white',
        label: 'Leadership Change',
        category: 'generic',
        color: 'white',
        tags: ['leadership', 'change', 'management', 'transition', 'strategy', 'direction', 'vision'],
        pngUrl: `${BASE}/white/generic/Leadership+change+white.png`,
    },
    {
        id: 'partnership-generic-white',
        label: 'Partnership',
        category: 'generic',
        color: 'white',
        tags: ['partnership', 'collaboration', 'alliance', 'joint', 'together', 'team', 'relations'],
        pngUrl: `${BASE}/white/generic/partnership+-+white.png`,
    },
    {
        id: 'revenue-generic-white',
        label: 'Revenue',
        category: 'generic',
        color: 'white',
        tags: ['revenue', 'income', 'sales', 'profit', 'money', 'earnings', 'roi'],
        pngUrl: `${BASE}/white/generic/Revenue+white.png`,
    },
    {
        id: 'user-experience-generic-white',
        label: 'User Experience',
        category: 'generic',
        color: 'white',
        tags: ['ux', 'user experience', 'design', 'usability', 'interface', 'journey', 'product'],
        pngUrl: `${BASE}/white/generic/user+experience.png`,
    },
    {
        id: 'user-interaction-generic-white',
        label: 'User Interaction',
        category: 'generic',
        color: 'white',
        tags: ['user', 'interaction', 'engagement', 'click', 'behavior', 'interface', 'action'],
        pngUrl: `${BASE}/white/generic/user+interaction-white.png`,
    },
    {
        id: 'customer-support-marketing-white',
        label: 'Customer Support',
        category: 'marketing',
        color: 'white',
        tags: ['customer', 'support', 'service', 'help', 'assistance', 'care', 'helpdesk'],
        pngUrl: `${BASE}/white/marketing/Customer+Support+white.png`,
    },
    {
        id: 'global-campaign-marketing-white',
        label: 'Global Campaign',
        category: 'marketing',
        color: 'white',
        tags: ['global', 'campaign', 'international', 'worldwide', 'reach', 'market', 'expansion'],
        pngUrl: `${BASE}/white/marketing/Global+Campaign+white.png`,
    },
    {
        id: 'keyword-search-marketing-white',
        label: 'Keyword Search',
        category: 'marketing',
        color: 'white',
        tags: ['keyword', 'search', 'seo', 'query', 'terms', 'discovery', 'targeting'],
        pngUrl: `${BASE}/white/marketing/Keyword+search+white.png`,
    },
    {
        id: 'marketing-automation-marketing-white',
        label: 'Marketing Automation',
        category: 'marketing',
        color: 'white',
        tags: ['automation', 'marketing', 'workflow', 'trigger', 'sequence', 'nurture', 'pipeline'],
        pngUrl: `${BASE}/white/marketing/Marketing+Automation+white.png`,
    },
    {
        id: 'network-option1-marketing-white',
        label: 'Network Option 1',
        category: 'marketing',
        color: 'white',
        tags: ['network', 'connection', 'infrastructure', 'nodes', 'web', 'ecosystem', 'platform'],
        pngUrl: `${BASE}/white/marketing/Network+Option+1+white.png`,
    },
    {
        id: 'network-option2-marketing-white',
        label: 'Network Option 2',
        category: 'marketing',
        color: 'white',
        tags: ['network', 'connection', 'infrastructure', 'nodes', 'web', 'ecosystem', 'platform'],
        pngUrl: `${BASE}/white/marketing/Network+Option+2+white.png`,
    },
    {
        id: 'responsive-marketing-white',
        label: 'Responsive',
        category: 'marketing',
        color: 'white',
        tags: ['responsive', 'mobile', 'adaptive', 'design', 'device', 'screen', 'layout'],
        pngUrl: `${BASE}/white/marketing/Responsive+White.png`,
    },
    {
        id: 'sitemap-marketing-white',
        label: 'Sitemap',
        category: 'marketing',
        color: 'white',
        tags: ['sitemap', 'structure', 'navigation', 'architecture', 'pages', 'crawl', 'index'],
        pngUrl: `${BASE}/white/marketing/Sitemap+white.png`,
    },
    {
        id: 'social-network-marketing-white',
        label: 'Social Network',
        category: 'marketing',
        color: 'white',
        tags: ['social', 'network', 'media', 'community', 'platform', 'engagement', 'followers'],
        pngUrl: `${BASE}/white/marketing/Social+Network+white.png`,
    },
    {
        id: 'team-building-marketing-white',
        label: 'Team Building',
        category: 'marketing',
        color: 'white',
        tags: ['team', 'building', 'people', 'culture', 'collaboration', 'hiring', 'talent'],
        pngUrl: `${BASE}/white/marketing/TeamBuilding+white.png`,
    },
    {
        id: 'active-search-seo-white',
        label: 'Active Search',
        category: 'seo',
        color: 'white',
        tags: ['search', 'find', 'lookup', 'discovery', 'research', 'query', 'seo'],
        pngUrl: `${BASE}/white/seo/Active+Search+white.png`,
    },
    {
        id: 'calendar-seo-white',
        label: 'Calendar',
        category: 'seo',
        color: 'white',
        tags: ['calendar', 'schedule', 'planning', 'time', 'date', 'events', 'meeting'],
        pngUrl: `${BASE}/white/seo/Calendar+white.png`,
    },
    {
        id: 'chat-seo-white',
        label: 'Chat',
        category: 'seo',
        color: 'white',
        tags: ['chat', 'message', 'conversation', 'communication', 'support', 'dialogue'],
        pngUrl: `${BASE}/white/seo/Chat+White.png`,
    },
    {
        id: 'cloud-sync-seo-white',
        label: 'Cloud Sync',
        category: 'seo',
        color: 'white',
        tags: ['cloud', 'sync', 'backup', 'storage', 'integration', 'data', 'upload'],
        pngUrl: `${BASE}/white/seo/Cloud+Sync+white.png`,
    },
    {
        id: 'coding-seo-white',
        label: 'Coding',
        category: 'seo',
        color: 'white',
        tags: ['coding', 'programming', 'development', 'engineering', 'software', 'code'],
        pngUrl: `${BASE}/white/seo/Coding+white.png`,
    },
    {
        id: 'data-analytics-seo-white',
        label: 'Data Analytics',
        category: 'seo',
        color: 'white',
        tags: ['data', 'analytics', 'insights', 'metrics', 'reporting', 'analysis', 'dashboard'],
        pngUrl: `${BASE}/white/seo/data+analytics+white.png`,
    },
    {
        id: 'data-download-seo-white',
        label: 'Data Download',
        category: 'seo',
        color: 'white',
        tags: ['data', 'download', 'export', 'transfer', 'extract', 'retrieve'],
        pngUrl: `${BASE}/white/seo/Data+Download+White.png`,
    },
    {
        id: 'email-marketing-option1-seo-white',
        label: 'Email Marketing Option 1',
        category: 'seo',
        color: 'white',
        tags: ['email', 'marketing', 'newsletter', 'outreach', 'campaign', 'inbox'],
        pngUrl: `${BASE}/white/seo/Email+Marketing+Option+1+white.png`,
    },
    {
        id: 'email-marketing-option2-seo-white',
        label: 'Email Marketing Option 2',
        category: 'seo',
        color: 'white',
        tags: ['email', 'marketing', 'newsletter', 'outreach', 'campaign', 'inbox'],
        pngUrl: `${BASE}/white/seo/Email+Marketing+Option+2+White.png`,
    },
    {
        id: 'increased-performance-seo-white',
        label: 'Increased Performance',
        category: 'seo',
        color: 'white',
        tags: ['performance', 'increase', 'improve', 'optimize', 'boost', 'efficiency', 'results'],
        pngUrl: `${BASE}/white/seo/Increased+Performance+white.png`,
    },
    {
        id: 'link-seo-white',
        label: 'Link',
        category: 'seo',
        color: 'white',
        tags: ['link', 'connect', 'integration', 'url', 'backlink', 'reference', 'chain'],
        pngUrl: `${BASE}/white/seo/Link+white.png`,
    },
    {
        id: 'online-support-seo-white',
        label: 'Online Support',
        category: 'seo',
        color: 'white',
        tags: ['online', 'support', 'helpdesk', 'service', 'chat', 'remote', 'assistance'],
        pngUrl: `${BASE}/white/seo/Online+Support+White.png`,
    },
    {
        id: 'seo-location-seo-white',
        label: 'SEO Location',
        category: 'seo',
        color: 'white',
        tags: ['seo', 'location', 'local', 'geo', 'map', 'targeting', 'search'],
        pngUrl: `${BASE}/white/seo/SEO+Location+White.png`,
    },
    {
        id: 'seo-option1-seo-white',
        label: 'SEO Option 1',
        category: 'seo',
        color: 'white',
        tags: ['seo', 'optimization', 'search', 'ranking', 'organic', 'visibility', 'engine'],
        pngUrl: `${BASE}/white/seo/SEO+Option+1+White.png`,
    },
    {
        id: 'seo-option2-seo-white',
        label: 'SEO Option 2',
        category: 'seo',
        color: 'white',
        tags: ['seo', 'optimization', 'search', 'ranking', 'organic', 'visibility', 'engine'],
        pngUrl: `${BASE}/white/seo/SEO+option+2+white.png`,
    },
    {
        id: 'seo-plugin-option2-seo-white',
        label: 'SEO Plugin Option 2',
        category: 'seo',
        color: 'white',
        tags: ['seo', 'plugin', 'tool', 'optimization', 'search', 'ranking', 'engine'],
        pngUrl: `${BASE}/white/seo/SEO+Plugin+option+2+white.png`,
    },
    {
        id: 'seo-plugin-seo-white',
        label: 'SEO Plugin',
        category: 'seo',
        color: 'white',
        tags: ['seo', 'plugin', 'tool', 'optimization', 'search', 'ranking', 'engine'],
        pngUrl: `${BASE}/white/seo/Seo+Plugin+White.png`,
    },
    {
        id: 'seo-seo-white',
        label: 'SEO',
        category: 'seo',
        color: 'white',
        tags: ['seo', 'search engine optimization', 'ranking', 'organic', 'visibility', 'traffic'],
        pngUrl: `${BASE}/white/seo/SEO+white.png`,
    },
    {
        id: 'target-seo-white',
        label: 'Target',
        category: 'seo',
        color: 'white',
        tags: ['target', 'audience', 'goal', 'focus', 'aim', 'precision', 'segment'],
        pngUrl: `${BASE}/white/seo/Target+white.png`,
    },
    {
        id: 'time-management-seo-white',
        label: 'Time Management',
        category: 'seo',
        color: 'white',
        tags: ['time', 'management', 'efficiency', 'planning', 'deadline', 'schedule', 'productivity'],
        pngUrl: `${BASE}/white/seo/Time+management+white.png`,
    },
    {
        id: 'traffic-seo-white',
        label: 'Traffic',
        category: 'seo',
        color: 'white',
        tags: ['traffic', 'visits', 'sessions', 'users', 'web', 'inbound', 'acquisition'],
        pngUrl: `${BASE}/white/seo/Traffic+white.png`,
    },
    {
        id: 'video-marketing-seo-white',
        label: 'Video Marketing',
        category: 'seo',
        color: 'white',
        tags: ['video', 'marketing', 'content', 'media', 'youtube', 'visual', 'campaign'],
        pngUrl: `${BASE}/white/seo/Video+marketing+White.png`,
    },
    {
        id: 'web-optimisation-seo-white',
        label: 'Web Optimisation',
        category: 'seo',
        color: 'white',
        tags: ['web', 'optimisation', 'performance', 'speed', 'core web vitals', 'loading', 'site'],
        pngUrl: `${BASE}/white/seo/Web+Optimisation+white.png`,
    },
]

export const iconLibrary: IconLibrary = {
    version: '1.0',
    baseUrl: BASE,
    icons: [...blackIcons, ...whiteIcons],
}
