import type { IconLibrary } from './schema'

export const iconLibrary: IconLibrary = {
    version: '1.0',
    baseUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons',
    icons: [
        {
            id: 'active-search',
            label: 'Active Search',
            category: 'search',
            tags: ['search', 'find', 'lookup', 'discovery', 'research', 'query'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Active+Search.png',
        },
        {
            id: 'adaptation-ai',
            label: 'Adaptation AI',
            category: 'ai',
            tags: ['ai', 'artificial intelligence', 'machine learning', 'adaptation', 'smart', 'automation'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Adaptation+Ai.png',
        },
        {
            id: 'app-development',
            label: 'App Development',
            category: 'technology',
            tags: ['app', 'development', 'mobile', 'software', 'build', 'product', 'engineering'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/App+development.png',
        },
        {
            id: 'calendar',
            label: 'Calendar',
            category: 'productivity',
            tags: ['calendar', 'schedule', 'planning', 'time', 'date', 'events', 'meeting'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Calendar.png',
        },
        {
            id: 'campaign-marketing',
            label: 'Campaign Marketing',
            category: 'marketing',
            tags: ['campaign', 'marketing', 'advertising', 'promotion', 'outreach', 'brand'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Campaign+marketing.png',
        },
        {
            id: 'chat',
            label: 'Chat',
            category: 'communication',
            tags: ['chat', 'message', 'conversation', 'communication', 'support', 'dialogue'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Chat.png',
        },
        {
            id: 'cloud-sync',
            label: 'Cloud Sync',
            category: 'technology',
            tags: ['cloud', 'sync', 'backup', 'storage', 'integration', 'data', 'upload'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Cloud+sync.png',
        },
        {
            id: 'coding',
            label: 'Coding',
            category: 'technology',
            tags: ['coding', 'programming', 'development', 'engineering', 'software', 'code'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Coding.png',
        },
        {
            id: 'company-growth',
            label: 'Company Growth',
            category: 'business',
            tags: ['growth', 'company', 'expansion', 'scale', 'business', 'success', 'progress'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Company+-growth.png',
        },
        {
            id: 'creative-content',
            label: 'Creative Content',
            category: 'marketing',
            tags: ['creative', 'content', 'design', 'media', 'storytelling', 'writing', 'copy'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Creative+content.png',
        },
        {
            id: 'customer-support',
            label: 'Customer Support',
            category: 'support',
            tags: ['customer', 'support', 'service', 'help', 'assistance', 'care', 'helpdesk'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Customer+support.png',
        },
        {
            id: 'data-analytics',
            label: 'Data Analytics',
            category: 'analytics',
            tags: ['data', 'analytics', 'insights', 'metrics', 'reporting', 'analysis', 'dashboard'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/data+analytics.png',
        },
        {
            id: 'data-download',
            label: 'Data Download',
            category: 'analytics',
            tags: ['data', 'download', 'export', 'transfer', 'extract', 'retrieve'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Data+Download.png',
        },
        {
            id: 'deploy',
            label: 'Deploy',
            category: 'technology',
            tags: ['deploy', 'launch', 'release', 'ship', 'publish', 'go-live', 'production'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Deploy.png',
        },
        {
            id: 'email-marketing-option2',
            label: 'Email Marketing Option 2',
            category: 'marketing',
            tags: ['email', 'marketing', 'newsletter', 'outreach', 'campaign', 'inbox'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Email+Marketing_Option2.png',
        },
        {
            id: 'email-marketing-option1',
            label: 'Email Marketing Option 1',
            category: 'marketing',
            tags: ['email', 'marketing', 'newsletter', 'outreach', 'campaign', 'inbox'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Email+Marketing-+Option+01.png',
        },
        {
            id: 'global-campaign',
            label: 'Global Campaign',
            category: 'marketing',
            tags: ['global', 'campaign', 'international', 'worldwide', 'reach', 'market', 'expansion'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Global+compaign.png',
        },
        {
            id: 'increase-performance',
            label: 'Increase Performance',
            category: 'analytics',
            tags: ['performance', 'increase', 'improve', 'optimize', 'boost', 'efficiency', 'results'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Increase+performance.png',
        },
        {
            id: 'keyword-search',
            label: 'Keyword Search',
            category: 'search',
            tags: ['keyword', 'search', 'seo', 'query', 'terms', 'discovery', 'targeting'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Keyword+search.png',
        },
        {
            id: 'leadership-change',
            label: 'Leadership Change',
            category: 'business',
            tags: ['leadership', 'change', 'management', 'transition', 'strategy', 'direction', 'vision'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Leadership+-Change.png',
        },
        {
            id: 'linking',
            label: 'Linking',
            category: 'technology',
            tags: ['link', 'connect', 'integration', 'url', 'backlink', 'reference', 'chain'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Linking.png',
        },
        {
            id: 'marketing-automation',
            label: 'Marketing Automation',
            category: 'marketing',
            tags: ['automation', 'marketing', 'workflow', 'trigger', 'sequence', 'nurture', 'pipeline'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Marketing+automation.png',
        },
        {
            id: 'network-option1',
            label: 'Network Option 1',
            category: 'technology',
            tags: ['network', 'connection', 'infrastructure', 'nodes', 'web', 'ecosystem', 'platform'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Network_Option+01.png',
        },
        {
            id: 'network-option2',
            label: 'Network Option 2',
            category: 'technology',
            tags: ['network', 'connection', 'infrastructure', 'nodes', 'web', 'ecosystem', 'platform'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Network_Option+02.png',
        },
        {
            id: 'online-support',
            label: 'Online Support',
            category: 'support',
            tags: ['online', 'support', 'helpdesk', 'service', 'chat', 'remote', 'assistance'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Online+Support.png',
        },
        {
            id: 'partnership',
            label: 'Partnership',
            category: 'business',
            tags: ['partnership', 'collaboration', 'alliance', 'joint', 'together', 'team', 'relations'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Partnership.png',
        },
        {
            id: 'responsive',
            label: 'Responsive',
            category: 'technology',
            tags: ['responsive', 'mobile', 'adaptive', 'design', 'device', 'screen', 'layout'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Responsive.png',
        },
        {
            id: 'revenue',
            label: 'Revenue',
            category: 'business',
            tags: ['revenue', 'income', 'sales', 'profit', 'money', 'earnings', 'roi'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Revenue.png',
        },
        {
            id: 'seo-location',
            label: 'SEO Location',
            category: 'seo',
            tags: ['seo', 'location', 'local', 'geo', 'map', 'targeting', 'search'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/SEO+location.png',
        },
        {
            id: 'seo-plugin-option1',
            label: 'SEO Plugin Option 1',
            category: 'seo',
            tags: ['seo', 'plugin', 'tool', 'optimization', 'search', 'ranking', 'engine'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/SEO+plugin_Option+01.png',
        },
        {
            id: 'seo-option1',
            label: 'SEO Option 1',
            category: 'seo',
            tags: ['seo', 'optimization', 'search', 'ranking', 'organic', 'visibility', 'engine'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/SEO_Option+01.png',
        },
        {
            id: 'sitemap',
            label: 'Sitemap',
            category: 'seo',
            tags: ['sitemap', 'structure', 'navigation', 'architecture', 'pages', 'crawl', 'index'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Sitemap.png',
        },
        {
            id: 'social-network',
            label: 'Social Network',
            category: 'marketing',
            tags: ['social', 'network', 'media', 'community', 'platform', 'engagement', 'followers'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Social+network.png',
        },
        {
            id: 'target-audience',
            label: 'Target Audience',
            category: 'marketing',
            tags: ['target', 'audience', 'persona', 'segment', 'demographic', 'reach', 'focus'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Target+audiance+.png',
        },
        {
            id: 'team-building',
            label: 'Team Building',
            category: 'business',
            tags: ['team', 'building', 'people', 'culture', 'collaboration', 'hiring', 'talent'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Team+building.png',
        },
        {
            id: 'thinking-process',
            label: 'Thinking Process',
            category: 'business',
            tags: ['thinking', 'process', 'strategy', 'planning', 'ideation', 'brainstorm', 'decision'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Thinking+process.png',
        },
        {
            id: 'time-management',
            label: 'Time Management',
            category: 'productivity',
            tags: ['time', 'management', 'efficiency', 'planning', 'deadline', 'schedule', 'productivity'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Time+management.png',
        },
        {
            id: 'traffic',
            label: 'Traffic',
            category: 'analytics',
            tags: ['traffic', 'visits', 'sessions', 'users', 'web', 'inbound', 'acquisition'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Traffic.png',
        },
        {
            id: 'user-experience',
            label: 'User Experience',
            category: 'technology',
            tags: ['ux', 'user experience', 'design', 'usability', 'interface', 'journey', 'product'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/User+experience+.png',
        },
        {
            id: 'user-interaction',
            label: 'User Interaction',
            category: 'technology',
            tags: ['user', 'interaction', 'engagement', 'click', 'behavior', 'interface', 'action'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/User+interaction.png',
        },
        {
            id: 'video-marketing',
            label: 'Video Marketing',
            category: 'marketing',
            tags: ['video', 'marketing', 'content', 'media', 'youtube', 'visual', 'campaign'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Video+marketing.png',
        },
        {
            id: 'web-optimisation',
            label: 'Web Optimisation',
            category: 'technology',
            tags: ['web', 'optimisation', 'performance', 'speed', 'core web vitals', 'loading', 'site'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Web+optimisation.png',
        },
        {
            id: 'laptop-settings',
            label: 'Laptop Settings',
            category: 'technology',
            tags: ['laptop', 'settings', 'configuration', 'device', 'setup', 'system', 'it'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Laptop+settings.png',
        },
        {
            id: 'search-optimisation-seo',
            label: 'Search Optimisation SEO',
            category: 'seo',
            tags: ['seo', 'search', 'optimisation', 'ranking', 'organic', 'visibility', 'engine'],
            pngUrl: 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons/Search+optimisation+-+SEO.png',
        },
    ],
}