import type { PresentationSchema } from './schema'

/** Template ids supported by getTemplateMasterSchema (for dropdown) */
export const TEMPLATE_OPTIONS = [
  { value: 'position2_2026', label: 'Position2 2026' },
] as const

export type TemplateId = (typeof TEMPLATE_OPTIONS)[number]['value']

/**
 * Returns the master schema for the given template id.
 * Template must match a known id (e.g. position2_2026); use TEMPLATE_OPTIONS for dropdown values.
 *
 * @param template - Template id from TEMPLATE_OPTIONS (e.g. 'position2_2026')
 * @returns Full presentation schema for that template
 */
export function getTemplateMasterSchema(template: string): PresentationSchema {
  if (template === 'position2_2026') {
    return buildTemplateSchema()
  }
  throw new Error(`Unknown template: ${template}. Supported: ${TEMPLATE_OPTIONS.map((t) => t.value).join(', ')}`)
}

/**
 * Runs once when template changes
 * Output is stored in DB / JSON file
 */
function buildTemplateSchema(): PresentationSchema {
  return {
    schemaVersion: '1.0',
    templateVersion: 'position2_2026',
    id: "1wYE4gy_iHhLzmI1ra4F5U3wf_DI_fPWIzA_uRzPFwpU",
    slides: [
      {
        slideKey: 'TITLE_SLIDE',
        order: 1,
        templateSlideObjectId: 'g3b56832a139_1_23', // from presentations.get
        description: 'Opening title slide',
        blocks: [
          {
            key: 'headline',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g3b56832a139_1_25',
            minChars: 10,
            maxChars: 20,
            description: 'Main presentation headline',
            content: '',
          },
          {
            key: 'topic_visual',
            type: 'IMAGE',
            role: 'SUPPORTING_VISUAL',
            usage: ['logo', 'topic_icon'],
            shapeId: 'g3b56832a139_1_24',
            description: 'Small supporting visual, not a hero image',
            content: '',
          },
        ],
      },
      {
        slideKey: 'COVER_SLIDE',
        order: 2,
        templateSlideObjectId: 'g392319e7c15_4_83',
        description: 'Cover slide with title, subtitle, date, and hero image',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g392319e7c15_4_85',
            minChars: 10,
            maxChars: 30,
            description: 'Main presentation headline',
            content: '',
          },
          {
            key: 'subtitle',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g392319e7c15_4_87',
            minChars: 10,
            maxChars: 30,
            description: 'Presentation subtitle or tagline',
            content: '',
          },
          {
            key: 'date',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g392319e7c15_4_86',
            minChars: 5,
            maxChars: 30,
            description: 'Month and year display (e.g., "February | 2026")',
            content: '',
          },
          // {
          //   key: 'hero_image',
          //   type: 'IMAGE',
          //   role: 'PRIMARY_VISUAL',
          //   usage: ['background', 'contextual_photo', 'hero'],
          //   shapeId: 'g392319e7c15_4_91',
          //   description: 'Large hero image on the right side of the slide',
          //   content: '',
          // },
          // {
          //   key: 'logo',
          //   type: 'IMAGE',
          //   role: 'SUPPORTING_VISUAL',
          //   usage: ['logo', 'branding'],
          //   shapeId: 'g392319e7c15_4_98',
          //   description: 'Company logo in top left corner',
          //   content: '',
          // },
        ],
      },
      {
        slideKey: 'TABLE_OF_CONTENTS',
        order: 3,
        description: 'Table of contents slide with numbered list of sections',
        templateSlideObjectId: 'g2380b89c92d_0_1',

        blocks: [
          {
            key: 'toc_items',
            type: 'TEXT',
            role: 'LIST',

            shapeId: 'g2380b89c92d_0_3', // BODY text box containing numbered list
            description: 'List of section titles shown in the table of contents',

            content: [],
            minItems: 3,
            maxItems: 8,
            itemConstraints: {
              minChars: 10,
              maxChars: 40,
              description: 'Concise section heading',
            },
          },
        ],
      },
      {
        slideKey: 'TWO_COLUMN_IMAGE_TEXT',
        order: 4,
        templateSlideObjectId: 'g3bd983d1368_1_0', // correct – matches the slide's objectId
        description: 'Two-column layout with images, headers, and bulleted text content',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g3bd983d1368_1_3', // correct – TITLE placeholder
            minChars: 15,
            maxChars: 40,
            description: 'Slide title describing the two-column content',
            content: '',
          },
          {
            key: 'left_image',
            type: 'IMAGE',
            role: 'PRIMARY_VISUAL',
            usage: ['contextual_photo', 'illustration'],
            shapeId: 'g3bd983d1368_1_5', // correct – left AdobeStock image
            description: 'Left column image',
            content: '',
          },
          {
            key: 'left_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bd983d1368_1_11', // correct – left bold 18pt header
            minChars: 10,
            maxChars: 40,
            description: 'Left column header (bold, colored, 18pt)',
            content: '',
          },
          {
            key: 'left_content',
            type: 'TEXT',
            role: 'LIST',
            shapeId: 'g3bd983d1368_1_12', // correct – left bulleted list
            minItems: 2,
            maxItems: 3,
            itemConstraints: {
              minChars: 30,
              maxChars: 100,
              description: 'Body text for each bulleted point'
            },
            description: 'Left column bulleted list with body text only',
            content: [],
          },
          {
            key: 'right_image',
            type: 'IMAGE',
            role: 'PRIMARY_VISUAL',
            usage: ['contextual_photo', 'illustration'],
            shapeId: 'g3bd983d1368_1_7', // correct – right AdobeStock image
            description: 'Right column image',
            content: '',
          },
          {
            key: 'right_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bd983d1368_1_13', // correct – right bold 18pt header
            minChars: 10,
            maxChars: 40,
            description: 'Right column header (bold, colored, 18pt)',
            content: '',
          },
          {
            key: 'right_content',
            type: 'TEXT',
            role: 'LIST',
            shapeId: 'g3bd983d1368_1_15', // ← FIXED: was wrong (1_14), now correct
            minItems: 2,
            maxItems: 3,
            itemConstraints: {
              minChars: 30,
              maxChars: 100,
              description: 'Body text for each bulleted point'
            },
            description: 'Right column bulleted list with body text only',
            content: [],
          },
        ],
      },
      {
        slideKey: 'THREE_COLUMN_IMAGE_TEXT',
        order: 5,
        templateSlideObjectId: 'g392319e7c15_4_327',
        description: 'Three-column layout with images, separate headers and body text',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g392319e7c15_4_328',
            minChars: 15,
            maxChars: 40,
            description: 'Slide title describing the three-column content',
            content: '',
          },
          {
            key: 'left_image',
            type: 'IMAGE',
            role: 'PRIMARY_VISUAL',
            usage: ['contextual_photo', 'illustration'],
            shapeId: 'g392319e7c15_4_335',
            description: 'Left column image',
            content: '',
          },
          {
            key: 'left_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_0',
            minChars: 25,
            maxChars: 40,
            description: 'Left column header (18pt bold, ACCENT5 color)',
            content: '',
          },
          {
            key: 'left_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_1',
            minChars: 40,
            maxChars: 130,
            description: 'Left column body text (14pt regular)',
            content: '',
          },
          {
            key: 'middle_image',
            type: 'IMAGE',
            role: 'PRIMARY_VISUAL',
            usage: ['contextual_photo', 'illustration'],
            shapeId: 'g392319e7c15_4_337',
            description: 'Middle column image',
            content: '',
          },
          {
            key: 'middle_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_2',
            minChars: 25,
            maxChars: 40,
            description: 'Middle column header (18pt bold, ACCENT3 color)',
            content: '',
          },
          {
            key: 'middle_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_5',
            minChars: 40,
            maxChars: 130,
            description: 'Middle column body text (14pt regular)',
            content: '',
          },
          {
            key: 'right_image',
            type: 'IMAGE',
            role: 'PRIMARY_VISUAL',
            usage: ['contextual_photo', 'illustration'],
            shapeId: 'g392319e7c15_4_336',
            description: 'Right column image',
            content: '',
          },
          {
            key: 'right_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_7',
            minChars: 25,
            maxChars: 40,
            description: 'Right column header (18pt bold, ACCENT6 color)',
            content: '',
          },
          {
            key: 'right_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_6',
            minChars: 40,
            maxChars: 130,
            description: 'Right column body text (14pt regular)',
            content: '',
          },
        ],
      },
      {
        slideKey: 'TWO_COLUMN_TEXT_ONLY',
        order: 6,
        templateSlideObjectId: 'g392319e7c15_4_0',
        description: 'Two-column text layout with headers and bulleted lists (no images)',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g392319e7c15_4_4',
            minChars: 15,
            maxChars: 60,
            description: 'Slide title describing the two-column content',
            content: '',
          },
          {
            key: 'left_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_8',
            minChars: 10,
            maxChars: 40,
            description: 'Left column header (18pt bold, ACCENT4 color)',
            content: '',
          },
          {
            key: 'left_content',
            type: 'TEXT',
            role: 'LIST',
            shapeId: 'g392319e7c15_4_29',
            minItems: 2,
            maxItems: 4,
            itemConstraints: {
              minChars: 30,
              maxChars: 160,
              description: 'Body text for each bulleted point'
            },
            description: 'Left column bulleted list (14pt, DARK1 color)',
            content: [],
          },
          {
            key: 'right_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_9',
            minChars: 10,
            maxChars: 40,
            description: 'Right column header (18pt bold, ACCENT3 color)',
            content: '',
          },
          {
            key: 'right_content',
            type: 'TEXT',
            role: 'LIST',
            shapeId: 'g3bec8eac249_0_10',
            minItems: 2,
            maxItems: 4,
            itemConstraints: {
              minChars: 30,
              maxChars: 160,
              description: 'Body text for each bulleted point'
            },
            description: 'Right column bulleted list (14pt, DARK1 color)',
            content: [],
          },
        ],
      },
      {
        slideKey: 'FOUR_COLUMN_TEXT_ONLY',
        order: 7,
        templateSlideObjectId: 'g392319e7c15_4_308',
        description: 'Four-column text layout (2x2 grid) with headers and body text (no images, no bullets)',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g392319e7c15_4_309',
            minChars: 15,
            maxChars: 60,
            description: 'Slide title describing the four-column content',
            content: '',
          },
          {
            key: 'top_left_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_11',
            minChars: 10,
            maxChars: 40,
            description: 'Top-left column header (18pt bold, ACCENT6 color)',
            content: '',
          },
          {
            key: 'top_left_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g392319e7c15_4_312',
            minChars: 40,
            maxChars: 200,
            description: 'Top-left column body text (14pt regular)',
            content: '',
          },
          {
            key: 'top_right_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_12',
            minChars: 10,
            maxChars: 40,
            description: 'Top-right column header (18pt bold, ACCENT2 color)',
            content: '',
          },
          {
            key: 'top_right_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_13',
            minChars: 40,
            maxChars: 200,
            description: 'Top-right column body text (14pt regular)',
            content: '',
          },
          {
            key: 'bottom_left_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_14',
            minChars: 10,
            maxChars: 40,
            description: 'Bottom-left column header (18pt bold, ACCENT3 color)',
            content: '',
          },
          {
            key: 'bottom_left_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_17',
            minChars: 40,
            maxChars: 200,
            description: 'Bottom-left column body text (14pt regular)',
            content: '',
          },
          {
            key: 'bottom_right_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_18',
            minChars: 10,
            maxChars: 40,
            description: 'Bottom-right column header (18pt bold, ACCENT5 color)',
            content: '',
          },
          {
            key: 'bottom_right_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_20',
            minChars: 40,
            maxChars: 200,
            description: 'Bottom-right column body text (14pt regular)',
            content: '',
          },
        ]
      },
      {
        slideKey: 'SIX_COLUMN_TEXT_ONLY',
        order: 8,
        templateSlideObjectId: 'g392319e7c15_4_285',
        description: 'Six-column text layout (2 rows × 3 columns grid) with headers and body text',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g392319e7c15_4_286',
            minChars: 15,
            maxChars: 60,
            description: 'Slide title describing the six-column content',
            content: '',
          },
          {
            key: 'top_left_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_21',
            minChars: 10,
            maxChars: 40,
            description: 'Top-left column header (18pt bold, ACCENT6 color)',
            content: '',
          },
          {
            key: 'top_left_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g392319e7c15_4_290',
            minChars: 40,
            maxChars: 200,
            description: 'Top-left column body text (14pt regular)',
            content: '',
          },
          {
            key: 'top_middle_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_22',
            minChars: 10,
            maxChars: 40,
            description: 'Top-middle column header (18pt bold, ACCENT5 color)',
            content: '',
          },
          {
            key: 'top_middle_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_23',
            minChars: 40,
            maxChars: 200,
            description: 'Top-middle column body text (14pt regular)',
            content: '',
          },
          {
            key: 'top_right_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_24',
            minChars: 10,
            maxChars: 40,
            description: 'Top-right column header (18pt bold, ACCENT2 color)',
            content: '',
          },
          {
            key: 'top_right_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_25',
            minChars: 40,
            maxChars: 200,
            description: 'Top-right column body text (14pt regular)',
            content: '',
          },
          {
            key: 'bottom_left_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_26',
            minChars: 10,
            maxChars: 40,
            description: 'Bottom-left column header (18pt bold, ACCENT3 color)',
            content: '',
          },
          {
            key: 'bottom_left_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_27',
            minChars: 40,
            maxChars: 200,
            description: 'Bottom-left column body text (14pt regular)',
            content: '',
          },
          {
            key: 'bottom_middle_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_29',
            minChars: 10,
            maxChars: 40,
            description: 'Bottom-middle column header (18pt bold, ACCENT4 color)',
            content: '',
          },
          {
            key: 'bottom_middle_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_28',
            minChars: 40,
            maxChars: 200,
            description: 'Bottom-middle column body text (14pt regular)',
            content: '',
          },
          {
            key: 'bottom_right_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_30',
            minChars: 10,
            maxChars: 40,
            description: 'Bottom-right column header (18pt bold, LIGHT2 color)',
            content: '',
          },
          {
            key: 'bottom_right_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_31',
            minChars: 40,
            maxChars: 200,
            description: 'Bottom-right column body text (14pt regular)',
            content: '',
          },
        ],
      },
      {
        slideKey: 'BULLETED_LIST_WITH_STATS',
        order: 9,
        templateSlideObjectId: 'g258f1f1ebd7_0_38',
        description: 'Two-section layout: left side with bulleted list, right side with 3 circular stat items',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g258f1f1ebd7_0_40',
            minChars: 15,
            maxChars: 60,
            description: 'Slide title',
            content: '',
          },
          {
            key: 'bullet_list',
            type: 'TEXT',
            role: 'LIST',
            shapeId: 'g25d65cb0895_1_508',
            minItems: 2,
            maxItems: 4,
            itemConstraints: {
              minChars: 50,
              maxChars: 220,
              description: 'Bulleted point with detailed content'
            },
            description: 'Left side bulleted list with detailed points',
            content: [],
          },
          {
            key: 'stat1_percentage',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g2380b89c92d_0_19',
            minChars: 2,
            maxChars: 10,
            description: 'Top stat percentage (28pt bold, centered, white text) - e.g., "86%"',
            content: '',
          },
          {
            key: 'stat1_label',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g2380b89c92d_0_20',
            minChars: 10,
            maxChars: 50,
            description: 'Top stat label/description (18pt bold)',
            content: '',
          },
          {
            key: 'stat2_percentage',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g2380b89c92d_0_166',
            minChars: 2,
            maxChars: 10,
            description: 'Middle stat percentage (28pt bold, centered, white text) - e.g., "35%"',
            content: '',
          },
          {
            key: 'stat2_label',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g2380b89c92d_0_163',
            minChars: 10,
            maxChars: 50,
            description: 'Middle stat label/description (18pt bold)',
            content: '',
          },
          {
            key: 'stat3_percentage',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g2380b89c92d_0_167',
            minChars: 2,
            maxChars: 10,
            description: 'Bottom stat percentage (28pt bold, centered, white text) - e.g., "45%"',
            content: '',
          },
          {
            key: 'stat3_label',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g2380b89c92d_0_165',
            minChars: 10,
            maxChars: 50,
            description: 'Bottom stat label/description (18pt bold)',
            content: '',
          },
        ],
      },
      {
        slideKey: 'BULLETED_LIST_WITH_LARGE_STAT',
        order: 10,
        templateSlideObjectId: 'g2380b89c92d_0_153',
        description: 'Two-section layout: left side with bulleted list, right side with one large circular stat',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g2380b89c92d_0_154',
            minChars: 15,
            maxChars: 60,
            description: 'Slide title',
            content: '',
          },
          {
            key: 'bullet_list',
            type: 'TEXT',
            role: 'LIST',
            shapeId: 'g2380b89c92d_0_155',
            minItems: 3,
            maxItems: 5,
            itemConstraints: {
              minChars: 80,
              maxChars: 250,
              description: 'Bulleted point with extensive detailed content'
            },
            description: 'Left side bulleted list with extensive points',
            content: [],
          },
          {
            key: 'stat_percentage',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g2380b89c92d_0_157',
            minChars: 2,
            maxChars: 10,
            description: 'Large stat percentage (72pt bold, centered, white text) - e.g., "86%"',
            content: '',
          },
          {
            key: 'stat_label',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g2380b89c92d_0_158',
            minChars: 20,
            maxChars: 80,
            description: 'Stat label/description (18pt bold, centered, white text, can be 2 lines)',
            content: '',
          },
        ],
      },
      {
        slideKey: 'TRANSITION_SLIDE',
        order: 11,
        templateSlideObjectId: 'g328ad9f718d_0_36',
        description: 'Simple transition slide with section title (images ignored)',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g328ad9f718d_0_43',
            minChars: 5,
            maxChars: 40,
            description: 'Section or transition title',
            content: '',
          },
        ],
      },
      {
        slideKey: 'ENGAGEMENT_SLIDE',
        order: 12,
        templateSlideObjectId: 'g3b5c40508b0_1_0',
        description: 'Engagement/Q&A slide with title and question prompt in white card',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g3b5c40508b0_1_1',
            minChars: 10,
            maxChars: 40,
            description: 'Slide title (e.g., "Engagement Slide", "Q&A", "Questions?")',
            content: '',
          },
          {
            key: 'question_prompt',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3b5c40508b0_1_8',
            minChars: 5,
            maxChars: 100,
            description: 'Question or prompt text displayed in the white card (e.g., "Question:", "What questions do you have?")',
            content: '',
          },
        ],
      },
      {
        slideKey: 'CONTACT_SLIDE',
        order: 13,
        templateSlideObjectId: 'g2380b89c92d_0_168',
        description: 'Contact/closing slide with company info, location, social media icons, and footer - no editable content blocks',
        blocks: [],
      },
      {
        slideKey: 'THANKS_SLIDE',
        order: 14,
        templateSlideObjectId: 'g380191f62e7_0_42',
        description: 'Thanks/closing slide - static design with no editable content blocks',
        blocks: [],
      }
    ],
  }
}
