import type { IconLibrary, PresentationSchema } from './schema'
import { iconLibrary } from './icon_library'

export const TEMPLATE_OPTIONS = [{ value: 'position2_2026', label: 'Position2 2026' }] as const

export type TemplateId = (typeof TEMPLATE_OPTIONS)[number]['value']

/** Returns the static presentation icon catalog used by template image blocks. */
export function getPresentationIconLibrary(): IconLibrary {
  return iconLibrary
}

export function getTemplateMasterSchema(template: string): PresentationSchema {
  if (template === 'position2_2026') {
    return buildTemplateSchema()
  }
  throw new Error(
    `Unknown template: ${template}. Supported: ${TEMPLATE_OPTIONS.map((t) => t.value).join(', ')}`
  )
}

function buildTemplateSchema(): PresentationSchema {
  return {
    schemaVersion: '1.0',
    templateVersion: 'position2_2026',
    id: '1wYE4gy_iHhLzmI1ra4F5U3wf_DI_fPWIzA_uRzPFwpU',
    slides: [
      {
        slideKey: 'TITLE_SLIDE',
        order: 1,
        templateSlideObjectId: 'g3b56832a139_1_23',
        description: 'Opening title slide',
        blocks: [
          {
            key: 'headline',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g3b56832a139_1_25',
            minChars: 10,
            maxChars: 20,
            description: 'Main presentation headline',
            content: '',
          },
          {
            key: 'topic_visual',
            type: 'IMAGE',
            role: 'SUPPORTING_VISUAL',
            source: 'icon_library',
            replaceable: false,
            usage: ['logo', 'topic_icon'],
            shapeId: 'g3b56832a139_1_24',
            description: 'Small supporting visual, not a hero image',
            content: '',
          },
        ],
      },
      {
        slideKey: 'COVER_SLIDE',
        order: 2,
        templateSlideObjectId: 'g392319e7c15_4_83',
        description: 'Cover slide with title, subtitle, date, and hero image',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g392319e7c15_4_85',
            minChars: 10,
            maxChars: 30,
            description: 'Main presentation headline',
            content: '',
          },
          {
            key: 'subtitle',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g392319e7c15_4_87',
            minChars: 10,
            maxChars: 30,
            description: 'Presentation subtitle or tagline',
            content: '',
          },
          {
            key: 'date',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g392319e7c15_4_86',
            minChars: 5,
            maxChars: 30,
            description: 'Month and year display (e.g., "February | 2026")',
            content: '',
          },
          {
            key: 'hero_image',
            type: 'IMAGE',
            role: 'PRIMARY_VISUAL',
            source: 'stock_photo',
            replaceable: false,
            usage: ['background', 'contextual_photo', 'hero'],
            shapeId: 'g392319e7c15_4_91',
            description: 'Large hero image on the right side of the slide',
            content: '',
          },
          {
            key: 'logo',
            type: 'IMAGE',
            role: 'SUPPORTING_VISUAL',
            source: 'icon_library',
            replaceable: false,
            usage: ['logo', 'branding'],
            shapeId: 'g392319e7c15_4_98',
            description: 'Company logo in top left corner',
            content: '',
          },
        ],
      },
      {
        slideKey: 'TABLE_OF_CONTENTS',
        order: 3,
        description: 'Table of contents slide with numbered list of sections',
        templateSlideObjectId: 'g2380b89c92d_0_1',
        blocks: [
          {
            key: 'toc_items',
            type: 'TEXT',
            role: 'LIST',
            shapeId: 'g2380b89c92d_0_3',
            description: 'List of section titles shown in the table of contents',
            content: [],
            minItems: 3,
            maxItems: 8,
            itemConstraints: {
              minChars: 10,
              maxChars: 40,
              description: 'Concise section heading',
            },
          },
        ],
      },
      {
        slideKey: 'TWO_COLUMN_IMAGE_TEXT',
        order: 4,
        templateSlideObjectId: 'g3bd983d1368_1_0',
        description: 'Two-column layout with images, headers, and bulleted text content',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g3bd983d1368_1_3',
            minChars: 15,
            maxChars: 40,
            description: 'Slide title describing the two-column content',
            content: '',
          },
          {
            key: 'left_image',
            type: 'IMAGE',
            role: 'PRIMARY_VISUAL',
            source: 'stock_photo',
            replaceable: false,
            usage: ['contextual_photo', 'illustration'],
            shapeId: 'g3bd983d1368_1_5',
            description: 'Left column image',
            content: '',
          },
          {
            key: 'left_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bd983d1368_1_11',
            minChars: 10,
            maxChars: 40,
            description: 'Left column header (bold, colored, 18pt)',
            content: '',
          },
          {
            key: 'left_content',
            type: 'TEXT',
            role: 'LIST',
            shapeId: 'g3bd983d1368_1_12',
            minItems: 2,
            maxItems: 3,
            itemConstraints: {
              minChars: 30,
              maxChars: 100,
              description: 'Body text for each bulleted point',
            },
            description: 'Left column bulleted list with body text only',
            content: [],
          },
          {
            key: 'right_image',
            type: 'IMAGE',
            role: 'PRIMARY_VISUAL',
            source: 'stock_photo',
            replaceable: false,
            usage: ['contextual_photo', 'illustration'],
            shapeId: 'g3bd983d1368_1_7',
            description: 'Right column image',
            content: '',
          },
          {
            key: 'right_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bd983d1368_1_13',
            minChars: 10,
            maxChars: 40,
            description: 'Right column header (bold, colored, 18pt)',
            content: '',
          },
          {
            key: 'right_content',
            type: 'TEXT',
            role: 'LIST',
            shapeId: 'g3bd983d1368_1_15',
            minItems: 2,
            maxItems: 3,
            itemConstraints: {
              minChars: 30,
              maxChars: 100,
              description: 'Body text for each bulleted point',
            },
            description: 'Right column bulleted list with body text only',
            content: [],
          },
        ],
      },
      {
        slideKey: 'THREE_COLUMN_IMAGE_TEXT',
        order: 5,
        templateSlideObjectId: 'g392319e7c15_4_327',
        description: 'Three-column layout with images, separate headers and body text',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g392319e7c15_4_328',
            minChars: 15,
            maxChars: 40,
            description: 'Slide title describing the three-column content',
            content: '',
          },
          {
            key: 'left_image',
            type: 'IMAGE',
            role: 'PRIMARY_VISUAL',
            source: 'stock_photo',
            replaceable: false,
            usage: ['contextual_photo', 'illustration'],
            shapeId: 'g392319e7c15_4_335',
            description: 'Left column image',
            content: '',
          },
          {
            key: 'left_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_0',
            minChars: 25,
            maxChars: 40,
            description: 'Left column header (18pt bold, ACCENT5 color)',
            content: '',
          },
          {
            key: 'left_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_1',
            minChars: 40,
            maxChars: 130,
            description: 'Left column body text (14pt regular)',
            content: '',
          },
          {
            key: 'middle_image',
            type: 'IMAGE',
            role: 'PRIMARY_VISUAL',
            source: 'stock_photo',
            replaceable: false,
            usage: ['contextual_photo', 'illustration'],
            shapeId: 'g392319e7c15_4_337',
            description: 'Middle column image',
            content: '',
          },
          {
            key: 'middle_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_2',
            minChars: 25,
            maxChars: 40,
            description: 'Middle column header (18pt bold, ACCENT3 color)',
            content: '',
          },
          {
            key: 'middle_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_5',
            minChars: 40,
            maxChars: 130,
            description: 'Middle column body text (14pt regular)',
            content: '',
          },
          {
            key: 'right_image',
            type: 'IMAGE',
            role: 'PRIMARY_VISUAL',
            source: 'stock_photo',
            replaceable: false,
            usage: ['contextual_photo', 'illustration'],
            shapeId: 'g392319e7c15_4_336',
            description: 'Right column image',
            content: '',
          },
          {
            key: 'right_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_7',
            minChars: 25,
            maxChars: 40,
            description: 'Right column header (18pt bold, ACCENT6 color)',
            content: '',
          },
          {
            key: 'right_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_6',
            minChars: 40,
            maxChars: 130,
            description: 'Right column body text (14pt regular)',
            content: '',
          },
        ],
      },
      {
        slideKey: 'TWO_COLUMN_TEXT_ONLY',
        order: 6,
        templateSlideObjectId: 'g392319e7c15_4_0',
        description: 'Two-column text layout with headers and bulleted lists (no images)',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g392319e7c15_4_4',
            minChars: 15,
            maxChars: 60,
            description: 'Slide title describing the two-column content',
            content: '',
          },
          {
            key: 'left_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_8',
            minChars: 10,
            maxChars: 40,
            description: 'Left column header (18pt bold, ACCENT4 color)',
            content: '',
          },
          {
            key: 'left_content',
            type: 'TEXT',
            role: 'LIST',
            shapeId: 'g392319e7c15_4_29',
            minItems: 2,
            maxItems: 4,
            itemConstraints: {
              minChars: 30,
              maxChars: 160,
              description: 'Body text for each bulleted point',
            },
            description: 'Left column bulleted list (14pt, DARK1 color)',
            content: [],
          },
          {
            key: 'right_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_9',
            minChars: 10,
            maxChars: 40,
            description: 'Right column header (18pt bold, ACCENT3 color)',
            content: '',
          },
          {
            key: 'right_content',
            type: 'TEXT',
            role: 'LIST',
            shapeId: 'g3bec8eac249_0_10',
            minItems: 2,
            maxItems: 4,
            itemConstraints: {
              minChars: 30,
              maxChars: 160,
              description: 'Body text for each bulleted point',
            },
            description: 'Right column bulleted list (14pt, DARK1 color)',
            content: [],
          },
        ],
      },
      {
        slideKey: 'FOUR_COLUMN_TEXT_ONLY',
        order: 7,
        templateSlideObjectId: 'g392319e7c15_4_308',
        description: 'Four-column text layout (2x2 grid) with headers and body text (no images, no bullets)',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g392319e7c15_4_309',
            minChars: 15,
            maxChars: 60,
            description: 'Slide title describing the four-column content',
            content: '',
          },
          {
            key: 'top_left_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_11',
            minChars: 10,
            maxChars: 40,
            description: 'Top-left column header (18pt bold, ACCENT6 color)',
            content: '',
          },
          {
            key: 'top_left_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g392319e7c15_4_312',
            minChars: 40,
            maxChars: 200,
            description: 'Top-left column body text (14pt regular)',
            content: '',
          },
          {
            key: 'top_right_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_12',
            minChars: 10,
            maxChars: 40,
            description: 'Top-right column header (18pt bold, ACCENT2 color)',
            content: '',
          },
          {
            key: 'top_right_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_13',
            minChars: 40,
            maxChars: 200,
            description: 'Top-right column body text (14pt regular)',
            content: '',
          },
          {
            key: 'bottom_left_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_14',
            minChars: 10,
            maxChars: 40,
            description: 'Bottom-left column header (18pt bold, ACCENT3 color)',
            content: '',
          },
          {
            key: 'bottom_left_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_17',
            minChars: 40,
            maxChars: 200,
            description: 'Bottom-left column body text (14pt regular)',
            content: '',
          },
          {
            key: 'bottom_right_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_18',
            minChars: 10,
            maxChars: 40,
            description: 'Bottom-right column header (18pt bold, ACCENT5 color)',
            content: '',
          },
          {
            key: 'bottom_right_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_20',
            minChars: 40,
            maxChars: 200,
            description: 'Bottom-right column body text (14pt regular)',
            content: '',
          },
        ],
      },
      {
        slideKey: 'SIX_COLUMN_TEXT_ONLY',
        order: 8,
        templateSlideObjectId: 'g392319e7c15_4_285',
        description: 'Six-column text layout (2 rows × 3 columns grid) with headers and body text',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g392319e7c15_4_286',
            minChars: 15,
            maxChars: 60,
            description: 'Slide title describing the six-column content',
            content: '',
          },
          {
            key: 'top_left_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_21',
            minChars: 10,
            maxChars: 40,
            description: 'Top-left column header (18pt bold, ACCENT6 color)',
            content: '',
          },
          {
            key: 'top_left_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g392319e7c15_4_290',
            minChars: 40,
            maxChars: 200,
            description: 'Top-left column body text (14pt regular)',
            content: '',
          },
          {
            key: 'top_middle_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_22',
            minChars: 10,
            maxChars: 40,
            description: 'Top-middle column header (18pt bold, ACCENT5 color)',
            content: '',
          },
          {
            key: 'top_middle_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_23',
            minChars: 40,
            maxChars: 200,
            description: 'Top-middle column body text (14pt regular)',
            content: '',
          },
          {
            key: 'top_right_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_24',
            minChars: 10,
            maxChars: 40,
            description: 'Top-right column header (18pt bold, ACCENT2 color)',
            content: '',
          },
          {
            key: 'top_right_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_25',
            minChars: 40,
            maxChars: 200,
            description: 'Top-right column body text (14pt regular)',
            content: '',
          },
          {
            key: 'bottom_left_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_26',
            minChars: 10,
            maxChars: 40,
            description: 'Bottom-left column header (18pt bold, ACCENT3 color)',
            content: '',
          },
          {
            key: 'bottom_left_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_27',
            minChars: 40,
            maxChars: 200,
            description: 'Bottom-left column body text (14pt regular)',
            content: '',
          },
          {
            key: 'bottom_middle_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_29',
            minChars: 10,
            maxChars: 40,
            description: 'Bottom-middle column header (18pt bold, ACCENT4 color)',
            content: '',
          },
          {
            key: 'bottom_middle_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_28',
            minChars: 40,
            maxChars: 200,
            description: 'Bottom-middle column body text (14pt regular)',
            content: '',
          },
          {
            key: 'bottom_right_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3bec8eac249_0_30',
            minChars: 10,
            maxChars: 40,
            description: 'Bottom-right column header (18pt bold, LIGHT2 color)',
            content: '',
          },
          {
            key: 'bottom_right_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3bec8eac249_0_31',
            minChars: 40,
            maxChars: 200,
            description: 'Bottom-right column body text (14pt regular)',
            content: '',
          },
        ],
      },
      {
        slideKey: 'BULLETED_LIST_WITH_STATS',
        order: 9,
        templateSlideObjectId: 'g258f1f1ebd7_0_38',
        description: 'Two-section layout: left side with bulleted list, right side with 3 circular stat items',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g258f1f1ebd7_0_40',
            minChars: 15,
            maxChars: 60,
            description: 'Slide title',
            content: '',
          },
          {
            key: 'bullet_list',
            type: 'TEXT',
            role: 'LIST',
            shapeId: 'g25d65cb0895_1_508',
            minItems: 2,
            maxItems: 4,
            itemConstraints: {
              minChars: 50,
              maxChars: 220,
              description: 'Bulleted point with detailed content',
            },
            description: 'Left side bulleted list with detailed points',
            content: [],
          },
          {
            key: 'stat1_percentage',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g2380b89c92d_0_19',
            minChars: 2,
            maxChars: 10,
            description: 'Top stat percentage (28pt bold, centered, white text) - e.g., "86%"',
            content: '',
          },
          {
            key: 'stat1_label',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g2380b89c92d_0_20',
            minChars: 10,
            maxChars: 50,
            description: 'Top stat label/description (18pt bold)',
            content: '',
          },
          {
            key: 'stat2_percentage',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g2380b89c92d_0_166',
            minChars: 2,
            maxChars: 10,
            description: 'Middle stat percentage (28pt bold, centered, white text) - e.g., "35%"',
            content: '',
          },
          {
            key: 'stat2_label',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g2380b89c92d_0_163',
            minChars: 10,
            maxChars: 50,
            description: 'Middle stat label/description (18pt bold)',
            content: '',
          },
          {
            key: 'stat3_percentage',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g2380b89c92d_0_167',
            minChars: 2,
            maxChars: 10,
            description: 'Bottom stat percentage (28pt bold, centered, white text) - e.g., "45%"',
            content: '',
          },
          {
            key: 'stat3_label',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g2380b89c92d_0_165',
            minChars: 10,
            maxChars: 50,
            description: 'Bottom stat label/description (18pt bold)',
            content: '',
          },
        ],
      },
      {
        slideKey: 'BULLETED_LIST_WITH_LARGE_STAT',
        order: 10,
        templateSlideObjectId: 'g2380b89c92d_0_153',
        description: 'Two-section layout: left side with bulleted list, right side with one large circular stat',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g2380b89c92d_0_154',
            minChars: 15,
            maxChars: 60,
            description: 'Slide title',
            content: '',
          },
          {
            key: 'bullet_list',
            type: 'TEXT',
            role: 'LIST',
            shapeId: 'g2380b89c92d_0_155',
            minItems: 3,
            maxItems: 5,
            itemConstraints: {
              minChars: 80,
              maxChars: 250,
              description: 'Bulleted point with extensive detailed content',
            },
            description: 'Left side bulleted list with extensive points',
            content: [],
          },
          {
            key: 'stat_percentage',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g2380b89c92d_0_157',
            minChars: 2,
            maxChars: 10,
            description: 'Large stat percentage (72pt bold, centered, white text) - e.g., "86%"',
            content: '',
          },
          {
            key: 'stat_label',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g2380b89c92d_0_158',
            minChars: 20,
            maxChars: 80,
            description: 'Stat label/description (18pt bold, centered, white text, can be 2 lines)',
            content: '',
          },
        ],
      },
      {
        slideKey: 'TRANSITION_SLIDE',
        order: 11,
        templateSlideObjectId: 'g328ad9f718d_0_36',
        description: 'Simple transition slide with section title (images ignored)',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g328ad9f718d_0_43',
            minChars: 5,
            maxChars: 40,
            description: 'Section or transition title',
            content: '',
          },
        ],
      },
      {
        slideKey: 'ENGAGEMENT_SLIDE',
        order: 12,
        templateSlideObjectId: 'g3b5c40508b0_1_0',
        description: 'Engagement/Q&A slide with title and question prompt in white card',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g3b5c40508b0_1_1',
            minChars: 10,
            maxChars: 40,
            description: 'Slide title (e.g., "Engagement Slide", "Q&A", "Questions?")',
            content: '',
          },
          {
            key: 'question_prompt',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3b5c40508b0_1_8',
            minChars: 5,
            maxChars: 100,
            description: 'Question or prompt text displayed in the white card',
            content: '',
          },
        ],
      },
      {
        slideKey: 'CONTACT_SLIDE',
        order: 13,
        templateSlideObjectId: 'g2380b89c92d_0_168',
        description: 'Contact/closing slide with company info, location, social media icons, and footer - no editable content blocks',
        blocks: [],
      },
      {
        slideKey: 'THANKS_SLIDE',
        order: 14,
        templateSlideObjectId: 'g380191f62e7_0_42',
        description: 'Thanks/closing slide - static design with no editable content blocks',
        blocks: [],
      },
      {
        slideKey: 'THREE_COLUMN_ICON_TEXT',
        order: 15,
        templateSlideObjectId: 'g2380b89c92d_0_57',
        description: 'Three-column layout with icon, header, and body text per column',
        blocks: [
          {
            key: 'title',
            type: 'TEXT',
            role: 'TITLE',
            shapeId: 'g2380b89c92d_0_58',
            minChars: 15,
            maxChars: 40,
            description: 'Slide title describing the three-column content',
            content: '',
          },
          {
            key: 'left_icon',
            type: 'IMAGE',
            role: 'SUPPORTING_VISUAL',
            source: 'icon_library',
            replaceable: true,
            usage: ['icon', 'icon_library'],
            shapeId: 'g2380b89c92d_0_68',
            description: 'Icon for left column — AI picks from icon library based on left column topic',
            content: '',
          },
          {
            key: 'left_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3eb47ec6107_0_15',
            minChars: 10,
            maxChars: 40,
            description: 'Left column header (18pt bold, ACCENT6 color)',
            content: '',
          },
          {
            key: 'left_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3eb47ec6107_0_16',
            minChars: 40,
            maxChars: 160,
            description: 'Left column body text (14pt regular, DARK1 color)',
            content: '',
          },
          {
            key: 'middle_icon',
            type: 'IMAGE',
            role: 'SUPPORTING_VISUAL',
            source: 'icon_library',
            replaceable: true,
            usage: ['icon', 'icon_library'],
            shapeId: 'g2380b89c92d_0_69',
            description: 'Icon for middle column — AI picks from icon library based on middle column topic',
            content: '',
          },
          {
            key: 'middle_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3eb47ec6107_0_17',
            minChars: 10,
            maxChars: 40,
            description: 'Middle column header (18pt bold, ACCENT5 color)',
            content: '',
          },
          {
            key: 'middle_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3eb47ec6107_0_20',
            minChars: 40,
            maxChars: 160,
            description: 'Middle column body text (14pt regular, DARK1 color)',
            content: '',
          },
          {
            key: 'right_icon',
            type: 'IMAGE',
            role: 'SUPPORTING_VISUAL',
            source: 'icon_library',
            replaceable: true,
            usage: ['icon', 'icon_library'],
            shapeId: 'g2380b89c92d_0_70',
            description: 'Right column icon — AI picks from icon library based on right column topic',
            content: '',
          },
          {
            key: 'right_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3eb47ec6107_0_21',
            minChars: 10,
            maxChars: 40,
            description: 'Right column header (18pt bold, ACCENT2 color)',
            content: '',
          },
          {
            key: 'right_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3eb47ec6107_0_22',
            minChars: 40,
            maxChars: 160,
            description: 'Right column body text (14pt regular, DARK1 color)',
            content: '',
          },
        ],
      },
      {
        slideKey: 'AGENDA_STAIRCASE',
        order: 16,
        templateSlideObjectId: 'g3e56ca19c4f_2_517',
        description: 'Five-item staircase agenda slide with colored accent shapes, item label and subtext per item',
        blocks: [
          {
            key: 'item1_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_534',
            minChars: 5,
            maxChars: 30,
            description: 'Agenda item 01 label (16pt bold, dark) — e.g. "Market Strategy"',
            content: '',
          },
          {
            key: 'item1_subtext',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_535',
            minChars: 20,
            maxChars: 60,
            description: 'Agenda item 01 subtext (12pt, gray, Poppins light) — ACCENT2 colored shape',
            content: '',
          },
          {
            key: 'item2_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_531',
            minChars: 5,
            maxChars: 30,
            description: 'Agenda item 02 label (16pt bold, dark) — e.g. "Product Overview"',
            content: '',
          },
          {
            key: 'item2_subtext',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_532',
            minChars: 20,
            maxChars: 60,
            description: 'Agenda item 02 subtext (12pt, gray, Poppins light) — ACCENT3 colored shape',
            content: '',
          },
          {
            key: 'item3_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_528',
            minChars: 5,
            maxChars: 30,
            description: 'Agenda item 03 label (16pt bold, dark) — e.g. "Competitive Analysis"',
            content: '',
          },
          {
            key: 'item3_subtext',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_529',
            minChars: 20,
            maxChars: 60,
            description: 'Agenda item 03 subtext (12pt, gray, Poppins light) — ACCENT4 colored shape',
            content: '',
          },
          {
            key: 'item4_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_525',
            minChars: 5,
            maxChars: 30,
            description: 'Agenda item 04 label (16pt bold, dark) — e.g. "Financial Summary"',
            content: '',
          },
          {
            key: 'item4_subtext',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_526',
            minChars: 20,
            maxChars: 60,
            description: 'Agenda item 04 subtext (12pt, gray, Poppins light) — ACCENT5 colored shape',
            content: '',
          },
          {
            key: 'item5_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_522',
            minChars: 5,
            maxChars: 30,
            description: 'Agenda item 05 label (16pt bold, dark) — e.g. "Next Steps"',
            content: '',
          },
          {
            key: 'item5_subtext',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_523',
            minChars: 20,
            maxChars: 60,
            description: 'Agenda item 05 subtext (12pt, gray, Poppins light) — ACCENT6 colored shape',
            content: '',
          },
        ],
      },
      {
        slideKey: 'AGENDA_TWO_COLUMN',
        order: 18,
        templateSlideObjectId: 'g3e56ca19c4f_2_541',
        description: 'Six-item two-column agenda slide with colored diamond accents, item label and subtext per item. Items 01-03 on left, 04-06 on right.',
        blocks: [
          {
            key: 'item1_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_548',
            minChars: 5,
            maxChars: 20,
            description: 'Agenda item 01 label (17pt bold, dark) — e.g. "Market Strategy"',
            content: '',
          },
          {
            key: 'item1_subtext',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_549',
            minChars: 20,
            maxChars: 50,
            description: 'Agenda item 01 subtext (13pt, gray, Poppins light) — ACCENT6 diamond accent',
            content: '',
          },
          {
            key: 'item2_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_550',
            minChars: 5,
            maxChars: 20,
            description: 'Agenda item 02 label (17pt bold, dark) — e.g. "Product Overview"',
            content: '',
          },
          {
            key: 'item2_subtext',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_551',
            minChars: 20,
            maxChars: 50,
            description: 'Agenda item 02 subtext (13pt, gray, Poppins light) — ACCENT5 diamond accent',
            content: '',
          },
          {
            key: 'item3_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_552',
            minChars: 5,
            maxChars: 20,
            description: 'Agenda item 03 label (17pt bold, dark) — e.g. "Competitive Analysis"',
            content: '',
          },
          {
            key: 'item3_subtext',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_553',
            minChars: 20,
            maxChars: 50,
            description: 'Agenda item 03 subtext (13pt, gray, Poppins light) — ACCENT4 diamond accent',
            content: '',
          },
          {
            key: 'item4_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_557',
            minChars: 5,
            maxChars: 20,
            description: 'Agenda item 04 label (17pt bold, dark) — e.g. "Financial Summary"',
            content: '',
          },
          {
            key: 'item4_subtext',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_558',
            minChars: 20,
            maxChars: 50,
            description: 'Agenda item 04 subtext (13pt, gray, Poppins light) — ACCENT2 diamond accent',
            content: '',
          },
          {
            key: 'item5_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_559',
            minChars: 5,
            maxChars: 20,
            description: 'Agenda item 05 label (17pt bold, dark) — e.g. "Growth Roadmap"',
            content: '',
          },
          {
            key: 'item5_subtext',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_560',
            minChars: 20,
            maxChars: 30,
            description: 'Agenda item 05 subtext (13pt, gray, Poppins light) — ACCENT1 diamond accent',
            content: '',
          },
          {
            key: 'item6_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_561',
            minChars: 5,
            maxChars: 20,
            description: 'Agenda item 06 label (17pt bold, dark) — e.g. "Next Steps"',
            content: '',
          },
          {
            key: 'item6_subtext',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_562',
            minChars: 20,
            maxChars: 50,
            description: 'Agenda item 06 subtext (13pt, gray, Poppins light) — LIGHT2 diamond accent',
            content: '',
          },

        ],
      },
      {
        slideKey: 'AGENDA_FIVE_COLUMN',
        order: 19,
        templateSlideObjectId: 'g3e56ca19c4f_2_569',
        description: 'Five-item horizontal agenda slide with tall colored accent cards, item label and subtext per item displayed in a single row',
        blocks: [
          {
            key: 'item1_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_575',
            minChars: 5,
            maxChars: 20,
            description: 'Agenda item 01 label (16pt bold, white) — ACCENT6 tall card',
            content: '',
          },
          {
            key: 'item1_subtext',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_576',
            minChars: 20,
            maxChars: 88,
            description: 'Agenda item 01 subtext (12pt, white, Poppins light) — ACCENT6 tall card',
            content: '',
          },
          {
            key: 'item2_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_583',
            minChars: 5,
            maxChars: 20,
            description: 'Agenda item 02 label (16pt bold, white) — ACCENT5 tall card',
            content: '',
          },
          {
            key: 'item2_subtext',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_584',
            minChars: 20,
            maxChars: 88,
            description: 'Agenda item 02 subtext (12pt, white, Poppins light) — ACCENT5 tall card',
            content: '',
          },
          {
            key: 'item3_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_579',
            minChars: 5,
            maxChars: 20,
            description: 'Agenda item 03 label (16pt bold, white) — ACCENT4 tall card',
            content: '',
          },
          {
            key: 'item3_subtext',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_580',
            minChars: 20,
            maxChars: 88,
            description: 'Agenda item 03 subtext (12pt, white, Poppins light) — ACCENT4 tall card',
            content: '',
          },
          {
            key: 'item4_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_591',
            minChars: 5,
            maxChars: 20,
            description: 'Agenda item 04 label (16pt bold, white) — ACCENT3 tall card',
            content: '',
          },
          {
            key: 'item4_subtext',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_592',
            minChars: 20,
            maxChars: 88,
            description: 'Agenda item 04 subtext (12pt, white, Poppins light) — ACCENT3 tall card',
            content: '',
          },
          {
            key: 'item5_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_587',
            minChars: 5,
            maxChars: 20,
            description: 'Agenda item 05 label (16pt bold, white) — LIGHT2 tall card',
            content: '',
          },
          {
            key: 'item5_subtext',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_588',
            minChars: 20,
            maxChars: 88,
            description: 'Agenda item 05 subtext (12pt, white, Poppins light) — LIGHT2 tall card',
            content: '',
          },
        ],
      },
      {
        slideKey: 'FOUR_BUBBLE_TEXT',
        order: 20,
        templateSlideObjectId: 'g3e56ca19c4f_2_627',
        description: 'Four-item bubble layout with colored circular accents connected by dashed lines to small indicator dots. Each bubble contains a bold white text label. Items displayed in a single row.',
        blocks: [
          {
            key: 'item1_text',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_643',
            minChars: 20,
            maxChars: 48,
            description: 'Item 1 text inside large circle (15pt bold, white, centered) — LIGHT2 bubble',
            content: '',
          },
          {
            key: 'item2_text',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_644',
            minChars: 20,
            maxChars: 48,
            description: 'Item 2 text inside large circle (15pt bold, white, centered) — ACCENT5 bubble',
            content: '',
          },
          {
            key: 'item3_text',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_645',
            minChars: 20,
            maxChars: 48,
            description: 'Item 3 text inside large circle (15pt bold, white, centered) — ACCENT4 bubble',
            content: '',
          },
          {
            key: 'item4_text',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_646',
            minChars: 20,
            maxChars: 48,
            description: 'Item 4 text inside large circle (15pt bold, white, centered) — ACCENT6 bubble',
            content: '',
          },
        ],
      },
      {
        slideKey: 'FIVE_CHEVRON_PROCESS',
        order: 21,
        templateSlideObjectId: 'g3e56ca19c4f_2_651',
        description: 'Five-item horizontal chevron process flow slide. Each item has a HOME_PLATE header label, a chevron shape with a large letter, a stage label below, and a body paragraph. Includes two zone labels on bottom arrows.',
        blocks: [
          // ── Chevron letters ──
          {
            key: 'chevron1_letter',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_656',
            minChars: 1,
            maxChars: 1,
            description: 'Large decorative letter inside chevron 1 (65pt bold, white, ACCENT2) — typically first letter of item1_stage',
            content: '',
          },
          {
            key: 'chevron2_letter',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_658',
            minChars: 1,
            maxChars: 1,
            description: 'Large decorative letter inside chevron 2 (65pt bold, white, ACCENT5) — typically first letter of item2_stage',
            content: '',
          },
          {
            key: 'chevron3_letter',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_660',
            minChars: 1,
            maxChars: 1,
            description: 'Large decorative letter inside chevron 3 (65pt bold, white, ACCENT4) — typically first letter of item3_stage',
            content: '',
          },
          {
            key: 'chevron4_letter',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_662',
            minChars: 1,
            maxChars: 1,
            description: 'Large decorative letter inside chevron 4 (65pt bold, white, ACCENT3) — typically first letter of item4_stage',
            content: '',
          },
          {
            key: 'chevron5_letter',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_664',
            minChars: 1,
            maxChars: 1,
            description: 'Large decorative letter inside chevron 5 (65pt bold, white, ACCENT6) — typically first letter of item5_stage',
            content: '',
          },

          // ── Item 1 (ACCENT2) ──
          {
            key: 'item1_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_675',
            minChars: 5,
            maxChars: 20,
            description: 'Item 1 header label on HOME_PLATE shape (11pt bold, white) — ACCENT2',
            content: '',
          },
          {
            key: 'item1_stage',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_665',
            minChars: 5,
            maxChars: 20,
            description: 'Item 1 stage label below chevron (15pt bold, dark, centered) — ACCENT2',
            content: '',
          },
          {
            key: 'item1_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_680',
            minChars: 40,
            maxChars: 168,
            description: 'Item 1 body paragraph (11pt light, gray, centered) — ACCENT2',
            content: '',
          },

          // ── Item 2 (ACCENT5) ──
          {
            key: 'item2_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_676',
            minChars: 5,
            maxChars: 20,
            description: 'Item 2 header label on HOME_PLATE shape (11pt bold, white) — ACCENT5',
            content: '',
          },
          {
            key: 'item2_stage',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_666',
            minChars: 5,
            maxChars: 20,
            description: 'Item 2 stage label below chevron (15pt bold, dark, centered) — ACCENT5',
            content: '',
          },
          {
            key: 'item2_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_681',
            minChars: 40,
            maxChars: 161,
            description: 'Item 2 body paragraph (11pt light, gray, centered) — ACCENT5',
            content: '',
          },

          // ── Item 3 (ACCENT4) ──
          {
            key: 'item3_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_677',
            minChars: 5,
            maxChars: 20,
            description: 'Item 3 header label on HOME_PLATE shape (11pt bold, white) — ACCENT4',
            content: '',
          },
          {
            key: 'item3_stage',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_667',
            minChars: 5,
            maxChars: 20,
            description: 'Item 3 stage label below chevron (15pt bold, dark, centered) — ACCENT4',
            content: '',
          },
          {
            key: 'item3_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_682',
            minChars: 40,
            maxChars: 166,
            description: 'Item 3 body paragraph (11pt light, gray, centered) — ACCENT4',
            content: '',
          },

          // ── Item 4 (ACCENT3) ──
          {
            key: 'item4_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_678',
            minChars: 5,
            maxChars: 20,
            description: 'Item 4 header label on HOME_PLATE shape (11pt bold, white) — ACCENT3',
            content: '',
          },
          {
            key: 'item4_stage',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_668',
            minChars: 5,
            maxChars: 20,
            description: 'Item 4 stage label below chevron (15pt bold, dark, centered) — ACCENT3',
            content: '',
          },
          {
            key: 'item4_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_683',
            minChars: 40,
            maxChars: 155,
            description: 'Item 4 body paragraph (11pt light, gray, centered) — ACCENT3',
            content: '',
          },

          // ── Item 5 (ACCENT6) ──
          {
            key: 'item5_header',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_679',
            minChars: 5,
            maxChars: 20,
            description: 'Item 5 header label on HOME_PLATE shape (11pt bold, white) — ACCENT6',
            content: '',
          },
          {
            key: 'item5_stage',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_669',
            minChars: 5,
            maxChars: 20,
            description: 'Item 5 stage label below chevron (15pt bold, dark, centered) — ACCENT6',
            content: '',
          },
          {
            key: 'item5_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_684',
            minChars: 40,
            maxChars: 159,
            description: 'Item 5 body paragraph (11pt light, gray, centered) — ACCENT6',
            content: '',
          },

          // ── Zone labels ──
          {
            key: 'enablement_zone_label',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_687',
            minChars: 5,
            maxChars: 20,
            description: 'Left arrow zone label (11pt bold, white, centered) — gray LEFT_ARROW',
            content: '',
          },
          {
            key: 'engagement_zone_label',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_688',
            minChars: 5,
            maxChars: 20,
            description: 'Right arrow zone label (11pt bold, white, centered) — gray RIGHT_ARROW',
            content: '',
          },
          {
            slideKey: 'FOUR_ROW_LETTER_LIST',
            order: 22,
            templateSlideObjectId: 'g3e56ca19c4f_2_689',
            description: 'Four-row horizontal layout with alternating dark/colored background bands. Each row has a large bold letter accent on the left and a bold statement text on the right.',
            blocks: [
              // ── Row letters ──
              {
                key: 'row1_letter',
                type: 'TEXT',
                role: 'BODY',
                shapeId: 'g3e56ca19c4f_2_701',
                minChars: 1,
                maxChars: 1,
                description: 'Large decorative letter for row 1 (47pt bold, white, Poppins) — typically first letter of row1_label',
                content: '',
              },
              {
                key: 'row2_letter',
                type: 'TEXT',
                role: 'BODY',
                shapeId: 'g3e56ca19c4f_2_702',
                minChars: 1,
                maxChars: 1,
                description: 'Large decorative letter for row 2 (47pt bold, white, Poppins) — typically first letter of row2_label',
                content: '',
              },
              {
                key: 'row3_letter',
                type: 'TEXT',
                role: 'BODY',
                shapeId: 'g3e56ca19c4f_2_703',
                minChars: 1,
                maxChars: 1,
                description: 'Large decorative letter for row 3 (47pt bold, white, Poppins) — typically first letter of row3_label',
                content: '',
              },
              {
                key: 'row4_letter',
                type: 'TEXT',
                role: 'BODY',
                shapeId: 'g3e56ca19c4f_2_704',
                minChars: 1,
                maxChars: 1,
                description: 'Large decorative letter for row 4 (47pt bold, white, Poppins) — typically first letter of row4_label',
                content: '',
              },

              // ── Row labels ──
              {
                key: 'row1_label',
                type: 'TEXT',
                role: 'SECTION_HEADER',
                shapeId: 'g3e56ca19c4f_2_705',
                minChars: 10,
                maxChars: 60,
                description: 'Row 1 statement text (19pt bold, white, Poppins) — dark navy background band',
                content: '',
              },
              {
                key: 'row2_label',
                type: 'TEXT',
                role: 'SECTION_HEADER',
                shapeId: 'g3e56ca19c4f_2_706',
                minChars: 10,
                maxChars: 60,
                description: 'Row 2 statement text (19pt bold, white, Poppins) — medium blue background band',
                content: '',
              },
              {
                key: 'row3_label',
                type: 'TEXT',
                role: 'SECTION_HEADER',
                shapeId: 'g3e56ca19c4f_2_707',
                minChars: 10,
                maxChars: 60,
                description: 'Row 3 statement text (19pt bold, white, Poppins) — dark slate background band',
                content: '',
              },
              {
                key: 'row4_label',
                type: 'TEXT',
                role: 'SECTION_HEADER',
                shapeId: 'g3e56ca19c4f_2_708',
                minChars: 10,
                maxChars: 60,
                description: 'Row 4 statement text (19pt bold, white, Poppins) — green background band',
                content: '',
              },
            ],
          }
        ],
      },
      {
        slideKey: 'FOUR_ROW_LETTER_LIST',
        order: 22,
        templateSlideObjectId: 'g3e56ca19c4f_2_689',
        description: 'Four-row horizontal layout with alternating dark/colored background bands. Each row has a large bold letter accent on the left and a bold statement text on the right.',
        blocks: [
          // ── Row letters ──
          {
            key: 'row1_letter',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_701',
            minChars: 1,
            maxChars: 1,
            description: 'Large decorative letter for row 1 (47pt bold, white, Poppins) — typically first letter of row1_label',
            content: '',
          },
          {
            key: 'row2_letter',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_702',
            minChars: 1,
            maxChars: 1,
            description: 'Large decorative letter for row 2 (47pt bold, white, Poppins) — typically first letter of row2_label',
            content: '',
          },
          {
            key: 'row3_letter',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_703',
            minChars: 1,
            maxChars: 1,
            description: 'Large decorative letter for row 3 (47pt bold, white, Poppins) — typically first letter of row3_label',
            content: '',
          },
          {
            key: 'row4_letter',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_704',
            minChars: 1,
            maxChars: 1,
            description: 'Large decorative letter for row 4 (47pt bold, white, Poppins) — typically first letter of row4_label',
            content: '',
          },

          // ── Row labels ──
          {
            key: 'row1_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_705',
            minChars: 10,
            maxChars: 60,
            description: 'Row 1 statement text (19pt bold, white, Poppins) — dark navy background band',
            content: '',
          },
          {
            key: 'row2_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_706',
            minChars: 10,
            maxChars: 60,
            description: 'Row 2 statement text (19pt bold, white, Poppins) — medium blue background band',
            content: '',
          },
          {
            key: 'row3_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_707',
            minChars: 10,
            maxChars: 60,
            description: 'Row 3 statement text (19pt bold, white, Poppins) — dark slate background band',
            content: '',
          },
          {
            key: 'row4_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_708',
            minChars: 10,
            maxChars: 60,
            description: 'Row 4 statement text (19pt bold, white, Poppins) — green background band',
            content: '',
          },
        ],
      },
      {
        slideKey: 'FOUR_DIAMOND_ICON_GRID',
        order: 23,
        templateSlideObjectId: 'g3e56ca19c4f_2_709',
        description: 'Four-item 2x2 grid layout with colored overlapping circle/diamond icon pairs. Each item has a bold label above and below its icon pair. Top-left and top-right items have labels above, bottom-left and bottom-right items have labels below.',
        blocks: [
          {
            key: 'top_left_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_725',
            minChars: 10,
            maxChars: 60,
            description: 'Top-left item label (16pt bold, DARK1, centered, Poppins) — positioned above the icon pair',
            content: '',
          },
          {
            key: 'bottom_left_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_726',
            minChars: 10,
            maxChars: 60,
            description: 'Bottom-left item label (16pt bold, DARK1, centered, Poppins) — positioned below the icon pair',
            content: '',
          },
          {
            key: 'top_right_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_727',
            minChars: 10,
            maxChars: 60,
            description: 'Top-right item label (16pt bold, DARK1, centered, Poppins) — positioned above the icon pair',
            content: '',
          },
          {
            key: 'bottom_right_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_728',
            minChars: 10,
            maxChars: 60,
            description: 'Bottom-right item label (16pt bold, DARK1, centered, Poppins) — positioned below the icon pair',
            content: '',
          },
        ],
      },
      {
        slideKey: 'FIVE_NODE_CIRCULAR_FLOW',
        order: 24,
        templateSlideObjectId: 'g3e56ca19c4f_2_729',
        description: 'Five-node circular hub-and-spoke flow diagram with colored ellipse nodes and white icon groups. Each node has a bold colored label. The center-bottom node (node 3) also supports an optional subtext line.',
        blocks: [
          {
            key: 'node1_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_795',
            minChars: 5,
            maxChars: 25,
            description: 'Top-left node label (16pt bold, green color, centered, Poppins) — may contain a vertical tab character \\u000b for a soft line break',
            content: '',
          },
          {
            key: 'node2_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_796',
            minChars: 5,
            maxChars: 25,
            description: 'Bottom-left node label (16pt bold, light blue color, centered, Poppins) — may contain a vertical tab character \\u000b for a soft line break',
            content: '',
          },
          {
            key: 'node3_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_797',
            minChars: 5,
            maxChars: 25,
            description: 'Top-center node label (16pt bold, gray color, centered, Poppins) — may contain a vertical tab character \\u000b for a soft line break',
            content: '',
          },
          {
            key: 'node4_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_798',
            minChars: 5,
            maxChars: 25,
            description: 'Bottom-center node label (16pt bold header + optional 12pt regular subtext, dark blue color, centered, Poppins) — supports a second paragraph for subtext such as a parenthetical detail',
            content: '',
          },
          {
            key: 'node5_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_799',
            minChars: 5,
            maxChars: 25,
            description: 'Top-right node label (16pt bold, purple color, centered, Poppins)',
            content: '',
          },
        ],
      },
      {
        slideKey: 'TWO_COLUMN_IMAGE_HEADLINE_BODY',
        order: 25,
        templateSlideObjectId: 'g3e56ca19c4f_2_863',
        description: 'Two-column layout with a large center image/graphic, a headline and body text on the left, and a headline and body text on the right. Left body text is right-aligned, right body text is left-aligned.',
        blocks: [
          {
            key: 'left_headline',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_868',
            minChars: 5,
            maxChars: 30,
            description: 'Left column headline (24pt bold, ACCENT4 color, centered, Poppins)',
            content: '',
          },
          {
            key: 'left_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_869',
            minChars: 40,
            maxChars: 100,
            description: 'Left column body text (16pt light, DARK1 color, right-aligned, Poppins)',
            content: '',
          },
          {
            key: 'right_headline',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_870',
            minChars: 5,
            maxChars: 30,
            description: 'Right column headline (24pt bold, ACCENT6 color, centered, Poppins)',
            content: '',
          },
          {
            key: 'right_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_871',
            minChars: 40,
            maxChars: 100,
            description: 'Right column body text (16pt light, DARK1 color, left-aligned, Poppins)',
            content: '',
          },
        ],
      },
      {
        slideKey: 'THREE_ROW_NUMBER_LABEL_BODY',
        order: 26,
        templateSlideObjectId: 'g3e56ca19c4f_2_872',
        description: 'Three-row layout with a human head silhouette graphic on the right split into three colored sections (purple/navy/cyan), each containing a white icon. On the left, each row has a right-aligned uppercase label, body text, and a large bold number that sits between the text and the head graphic.',
        blocks: [
          // ── Row 1 (ACCENT6 — purple) ──
          {
            key: 'row1_number',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_882',
            minChars: 1,
            maxChars: 2,
            description: 'Row 1 large number (65pt bold, ACCENT6 purple color, Poppins) — sits between left text and the head graphic, visually aligned with the top purple section. Typically "1".',
            content: '',
          },
          {
            key: 'row1_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_883',
            minChars: 3,
            maxChars: 20,
            description: 'Row 1 uppercase section label (19pt bold, ACCENT6 purple color, right-aligned, Poppins) — appears above the row 1 body text e.g. "PLANNING"',
            content: '',
          },
          {
            key: 'row1_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_884',
            minChars: 40,
            maxChars: 100,
            description: 'Row 1 body text (12pt medium, DARK1 color, right-aligned, Poppins) — appears below row 1 label on the left side of the slide',
            content: '',
          },

          // ── Row 2 (ACCENT5 — navy blue) ──
          {
            key: 'row2_number',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_885',
            minChars: 1,
            maxChars: 2,
            description: 'Row 2 large number (65pt bold, ACCENT5 navy color, Poppins) — sits between left text and the head graphic, visually aligned with the middle navy section. Typically "2".',
            content: '',
          },
          {
            key: 'row2_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_886',
            minChars: 3,
            maxChars: 20,
            description: 'Row 2 uppercase section label (19pt bold, ACCENT5 navy color, right-aligned, Poppins) — appears above the row 2 body text e.g. "IDEA"',
            content: '',
          },
          {
            key: 'row2_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_887',
            minChars: 40,
            maxChars: 100,
            description: 'Row 2 body text (12pt medium, DARK1 color, right-aligned, Poppins) — appears below row 2 label on the left side of the slide',
            content: '',
          },

          // ── Row 3 (ACCENT4 — cyan) ──
          {
            key: 'row3_number',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_888',
            minChars: 1,
            maxChars: 2,
            description: 'Row 3 large number (65pt bold, ACCENT4 cyan color, Poppins) — sits between left text and the head graphic, visually aligned with the bottom cyan section. Typically "3".',
            content: '',
          },
          {
            key: 'row3_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_889',
            minChars: 3,
            maxChars: 20,
            description: 'Row 3 uppercase section label (19pt bold, ACCENT4 cyan color, right-aligned, Poppins) — appears above the row 3 body text e.g. "SOLUTION"',
            content: '',
          },
          {
            key: 'row3_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_890',
            minChars: 40,
            maxChars: 100,
            description: 'Row 3 body text (12pt medium, DARK1 color, right-aligned, Poppins) — appears below row 3 label on the left side of the slide',
            content: '',
          },
        ],
      },
      {
        slideKey: 'THREE_COLUMN_STAT_BULLET_LIST',
        order: 27,
        templateSlideObjectId: 'g3e56ca19c4f_2_891',
        description: 'Three-column layout. Each column has: a colored rounded rectangle header bar at top with a bold white label; three separate bullet point text boxes in the body area (one bullet each, stacked vertically); and a large bold colored stat value on a tinted rounded card at the bottom. Two gray horizontal divider lines separate the header, body, and stat sections. Columns use ACCENT3 green, ACCENT5 navy, ACCENT6 purple.',
        blocks: [
          // ── Column 1 (ACCENT3 — green) ──
          {
            key: 'col1_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_902',
            minChars: 3,
            maxChars: 20,
            description: 'Column 1 header label (19pt bold, white, centered, Poppins) — on ACCENT3 green rounded bar e.g. "BUDGET"',
            content: '',
          },
          {
            key: 'col1_bullet1',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_905',
            minChars: 40,
            maxChars: 80,
            description: 'Column 1 first bullet point (12pt regular, DARK1, bulleted, Poppins) — top body text box',
            content: '',
          },
          {
            key: 'col1_bullet2',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e5704fc447_0_8',
            minChars: 40,
            maxChars: 80,
            description: 'Column 1 second bullet point (12pt regular, DARK1, bulleted, Poppins) — middle body text box',
            content: '',
          },
          {
            key: 'col1_bullet3',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e5704fc447_0_9',
            minChars: 40,
            maxChars: 80,
            description: 'Column 1 third bullet point (12pt regular, DARK1, bulleted, Poppins) — bottom body text box',
            content: '',
          },
          {
            key: 'col1_stat',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_908',
            minChars: 2,
            maxChars: 10,
            description: 'Column 1 stat value (29pt bold, ACCENT3 green, centered, Poppins) — large value on tinted green rounded card at bottom e.g. "$87,000"',
            content: '',
          },

          // ── Column 2 (ACCENT5 — navy) ──
          {
            key: 'col2_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_903',
            minChars: 3,
            maxChars: 20,
            description: 'Column 2 header label (19pt bold, white, centered, Poppins) — on ACCENT5 navy rounded bar e.g. "SPENDING"',
            content: '',
          },
          {
            key: 'col2_bullet1',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e5704fc447_0_3',
            minChars: 40,
            maxChars: 80,
            description: 'Column 2 first bullet point (12pt regular, DARK1, bulleted, Poppins) — top body text box',
            content: '',
          },
          {
            key: 'col2_bullet2',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e5704fc447_0_4',
            minChars: 40,
            maxChars: 80,
            description: 'Column 2 second bullet point (12pt regular, DARK1, bulleted, Poppins) — middle body text box',
            content: '',
          },
          {
            key: 'col2_bullet3',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e5704fc447_0_5',
            minChars: 40,
            maxChars: 80,
            description: 'Column 2 third bullet point (12pt regular, DARK1, bulleted, Poppins) — bottom body text box',
            content: '',
          },
          {
            key: 'col2_stat',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_909',
            minChars: 2,
            maxChars: 15,
            description: 'Column 2 stat value (29pt bold, ACCENT5 navy, centered, Poppins) — large value on tinted navy rounded card at bottom e.g. "$45,000"',
            content: '',
          },

          // ── Column 3 (ACCENT6 — purple) ──
          {
            key: 'col3_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_904',
            minChars: 3,
            maxChars: 20,
            description: 'Column 3 header label (19pt bold, white, centered, Poppins) — on ACCENT6 purple rounded bar e.g. "SAVING"',
            content: '',
          },
          {
            key: 'col3_bullet1',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e5704fc447_0_6',
            minChars: 40,
            maxChars: 80,
            description: 'Column 3 first bullet point (12pt regular, DARK1, bulleted, Poppins) — top body text box',
            content: '',
          },
          {
            key: 'col3_bullet2',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e5704fc447_0_2',
            minChars: 40,
            maxChars: 80,
            description: 'Column 3 second bullet point (12pt regular, DARK1, bulleted, Poppins) — middle body text box',
            content: '',
          },
          {
            key: 'col3_bullet3',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e5704fc447_0_7',
            minChars: 40,
            maxChars: 80,
            description: 'Column 3 third bullet point (12pt regular, DARK1, bulleted, Poppins) — bottom body text box',
            content: '',
          },
          {
            key: 'col3_stat',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_910',
            minChars: 2,
            maxChars: 10,
            description: 'Column 3 stat value (29pt bold, ACCENT6 purple, centered, Poppins) — large value on tinted purple rounded card at bottom e.g. "$42,000"',
            content: '',
          },
        ],
      },
      {
        slideKey: 'THREE_ROW_ARROW_ICON_BODY_STAT',
        order: 28,
        templateSlideObjectId: 'g3e56ca19c4f_2_912',
        description: 'Three-row horizontal arrow/chevron layout. Each row has: a colored circle on the left with a static white icon; a HOME_PLATE shaped body text area in the center on a lighter accent color; and a darker HOME_PLATE arrow shape on the right with a large bold white stat value. Rows use green (ACCENT3), navy (ACCENT5), and purple (ACCENT6) color families.',
        blocks: [
          // ── Row 1 (green) ──
          {
            key: 'row1_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_928',
            minChars: 40,
            maxChars: 110,
            description: 'Row 1 body text (12pt medium, white/LIGHT1, left-aligned, Poppins) — inside the lighter green HOME_PLATE center shape',
            content: '',
          },
          {
            key: 'row1_stat',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_931',
            minChars: 2,
            maxChars: 15,
            description: 'Row 1 stat value (29pt bold, white/LIGHT1, Poppins) — inside the dark green arrow HOME_PLATE on the right e.g. "$1,000,000"',
            content: '',
          },

          // ── Row 2 (navy) ──
          {
            key: 'row2_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_929',
            minChars: 40,
            maxChars: 110,
            description: 'Row 2 body text (12pt medium, white/LIGHT1, left-aligned, Poppins) — inside the lighter navy HOME_PLATE center shape',
            content: '',
          },
          {
            key: 'row2_stat',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_932',
            minChars: 2,
            maxChars: 15,
            description: 'Row 2 stat value (29pt bold, white/LIGHT1, Poppins) — inside the dark navy arrow HOME_PLATE on the right e.g. "$900,000"',
            content: '',
          },

          // ── Row 3 (purple) ──
          {
            key: 'row3_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_930',
            minChars: 40,
            maxChars: 110,
            description: 'Row 3 body text (12pt medium, white/LIGHT1, left-aligned, Poppins) — inside the lighter purple HOME_PLATE center shape',
            content: '',
          },
          {
            key: 'row3_stat',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_933',
            minChars: 2,
            maxChars: 15,
            description: 'Row 3 stat value (29pt bold, white/LIGHT1, Poppins) — inside the dark purple arrow HOME_PLATE on the right e.g. "$1,200,000"',
            content: '',
          },
        ],
      },
      {
        slideKey: 'FIVE_ROW_ICON_LABEL_BODY',
        order: 29,
        templateSlideObjectId: 'g3e56ca19c4f_2_934',
        description: 'Five-row list layout. Each row has: a large light gray number on the far left (static, decorative); a white circle with a static icon outline; a solid colored rounded rectangle on the left with a bold white label; and a tinted rounded rectangle on the right with dark body text. Each row uses a distinct color — purple, navy, cyan/light blue, green, orange.',
        blocks: [
          // ── Row 1 (purple) ──
          {
            key: 'row1_number',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_938',
            minChars: 1,
            maxChars: 2,
            description: 'Row 1 large decorative number (36pt bold, light gray, right-aligned, Poppins) — typically "1"',
            content: '',
          },
          {
            key: 'row1_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_946',
            minChars: 5,
            maxChars: 35,
            description: 'Row 1 label (15pt bold, white, left-aligned, Poppins) — inside solid purple rounded rectangle e.g. "Improved User Satisfaction"',
            content: '',
          },
          {
            key: 'row1_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_948',
            minChars: 20,
            maxChars: 100,
            description: 'Row 1 body text (15pt regular, DARK1, left-aligned, Poppins) — inside tinted purple rounded rectangle on the right',
            content: '',
          },
      
          // ── Row 2 (navy blue) ──
          {
            key: 'row2_number',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_939',
            minChars: 1,
            maxChars: 2,
            description: 'Row 2 large decorative number (36pt bold, light gray, right-aligned, Poppins) — typically "2"',
            content: '',
          },
          {
            key: 'row2_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_953',
            minChars: 5,
            maxChars: 35,
            description: 'Row 2 label (15pt bold, white, left-aligned, Poppins) — inside solid navy rounded rectangle e.g. "Stronger Brand Perception"',
            content: '',
          },
          {
            key: 'row2_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_955',
            minChars: 20,
            maxChars: 100,
            description: 'Row 2 body text (15pt regular, DARK1, left-aligned, Poppins) — inside tinted navy rounded rectangle on the right',
            content: '',
          },
      
          // ── Row 3 (cyan/light blue) ──
          {
            key: 'row3_number',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_940',
            minChars: 1,
            maxChars: 2,
            description: 'Row 3 large decorative number (36pt bold, light gray, right-aligned, Poppins) — typically "3"',
            content: '',
          },
          {
            key: 'row3_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_960',
            minChars: 5,
            maxChars: 35,
            description: 'Row 3 label (15pt bold, white, left-aligned, Poppins) — inside solid cyan rounded rectangle e.g. "Reduced Sales Cycle"',
            content: '',
          },
          {
            key: 'row3_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_962',
            minChars: 20,
            maxChars: 100,
            description: 'Row 3 body text (15pt regular, DARK1, left-aligned, Poppins) — inside tinted cyan rounded rectangle on the right',
            content: '',
          },
      
          // ── Row 4 (green) ──
          {
            key: 'row4_number',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_941',
            minChars: 1,
            maxChars: 2,
            description: 'Row 4 large decorative number (36pt bold, light gray, right-aligned, Poppins) — typically "4"',
            content: '',
          },
          {
            key: 'row4_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_967',
            minChars: 5,
            maxChars: 35,
            description: 'Row 4 label (15pt bold, white, left-aligned, Poppins) — inside solid green rounded rectangle e.g. "Competitive Advantage"',
            content: '',
          },
          {
            key: 'row4_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_969',
            minChars: 20,
            maxChars: 100,
            description: 'Row 4 body text (15pt regular, DARK1, left-aligned, Poppins) — inside tinted green rounded rectangle on the right',
            content: '',
          },
      
          // ── Row 5 (orange) ──
          {
            key: 'row5_number',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_942',
            minChars: 1,
            maxChars: 2,
            description: 'Row 5 large decorative number (36pt bold, light gray, right-aligned, Poppins) — typically "5"',
            content: '',
          },
          {
            key: 'row5_label',
            type: 'TEXT',
            role: 'SECTION_HEADER',
            shapeId: 'g3e56ca19c4f_2_974',
            minChars: 5,
            maxChars: 35,
            description: 'Row 5 label (15pt bold, white, left-aligned, Poppins) — inside solid orange rounded rectangle e.g. "Increased Customer Lifetime Value"',
            content: '',
          },
          {
            key: 'row5_body',
            type: 'TEXT',
            role: 'BODY',
            shapeId: 'g3e56ca19c4f_2_976',
            minChars: 20,
            maxChars: 100,
            description: 'Row 5 body text (15pt regular, DARK1, left-aligned, Poppins) — inside tinted orange rounded rectangle on the right',
            content: '',
          },
        ],
      }
    ],
  }
}