/**
 * Google Ads GAQL Resources (Tables)
 * Reference: https://developers.google.com/google-ads/api/fields/v17/overview
 */

import type { GaqlResource } from './types.js'

export const GAQL_RESOURCES: GaqlResource[] = [
  {
    name: 'campaign',
    category: 'campaign',
    description: 'Campaign-level performance and configuration',
    fields: [
      'campaign.id', 'campaign.name', 'campaign.status', 'campaign.advertising_channel_type',
      'campaign.advertising_channel_sub_type', 'campaign.start_date', 'campaign.end_date',
      'campaign.serving_status', 'campaign.bidding_strategy_type', 'campaign.campaign_budget',
      'campaign.optimization_score', 'campaign.tracking_url_template', 'campaign.experiment_type',
      'campaign.network_settings.target_google_search', 'campaign.network_settings.target_search_network',
      'campaign.network_settings.target_content_network', 'campaign.network_settings.target_partner_search_network',
    ],
    requiredFields: ['campaign.id', 'campaign.name', 'campaign.status'],
    supportsSegmentsDate: true,
    supportsMetrics: true,
  },
  {
    name: 'campaign_budget',
    category: 'campaign',
    description: 'Campaign budget configuration',
    fields: ['campaign_budget.id', 'campaign_budget.name', 'campaign_budget.amount_micros', 'campaign_budget.delivery_method', 'campaign_budget.status', 'campaign_budget.period'],
    requiredFields: ['campaign_budget.id'],
    supportsSegmentsDate: false,
    supportsMetrics: false,
  },
  {
    name: 'campaign_criterion',
    category: 'campaign',
    description: 'Campaign-level targeting criteria (locations, languages, devices)',
    fields: ['campaign.id', 'campaign.name', 'campaign_criterion.criterion_id', 'campaign_criterion.type', 'campaign_criterion.negative', 'campaign_criterion.location.geo_target_constant', 'campaign_criterion.language.language_constant', 'campaign_criterion.device.type'],
    requiredFields: ['campaign.id'],
    supportsSegmentsDate: false,
    supportsMetrics: false,
    notes: 'Snapshot resource - no segments.date support',
  },
  {
    name: 'ad_group',
    category: 'ad_group',
    description: 'Ad group performance and configuration',
    fields: ['ad_group.id', 'ad_group.name', 'ad_group.status', 'ad_group.type', 'ad_group.cpc_bid_micros', 'ad_group.cpm_bid_micros', 'ad_group.target_cpa_micros', 'ad_group.target_roas', 'ad_group.campaign'],
    requiredFields: ['campaign.id', 'campaign.status', 'ad_group.id', 'ad_group.name'],
    supportsSegmentsDate: true,
    supportsMetrics: true,
  },
  {
    name: 'ad_group_criterion',
    category: 'ad_group',
    description: 'Ad group-level criteria (keywords, audiences, demographics)',
    fields: ['ad_group_criterion.criterion_id', 'ad_group_criterion.type', 'ad_group_criterion.status', 'ad_group_criterion.negative', 'ad_group_criterion.keyword.text', 'ad_group_criterion.keyword.match_type', 'ad_group_criterion.quality_info.quality_score', 'ad_group_criterion.quality_info.creative_quality_score', 'ad_group_criterion.quality_info.post_click_quality_score', 'ad_group_criterion.quality_info.search_predicted_ctr'],
    requiredFields: ['ad_group.id', 'ad_group_criterion.criterion_id'],
    supportsSegmentsDate: true,
    supportsMetrics: true,
  },
  {
    name: 'keyword_view',
    category: 'keyword',
    description: 'Keyword performance with quality score',
    fields: ['campaign.id', 'campaign.name', 'campaign.status', 'ad_group.id', 'ad_group.name', 'ad_group_criterion.keyword.text', 'ad_group_criterion.keyword.match_type', 'ad_group_criterion.quality_info.quality_score', 'ad_group_criterion.quality_info.quality_score_bucket', 'ad_group_criterion.criterion_id', 'ad_group_criterion.status'],
    requiredFields: ['campaign.id', 'campaign.status'],
    supportsSegmentsDate: true,
    supportsMetrics: true,
  },
  {
    name: 'ad_group_ad',
    category: 'ad',
    description: 'Ad-level performance (RSA, image, video, etc.)',
    fields: ['ad_group_ad.ad.id', 'ad_group_ad.ad.type', 'ad_group_ad.ad.name', 'ad_group_ad.ad_strength', 'ad_group_ad.status', 'ad_group_ad.ad.final_urls', 'ad_group_ad.ad.final_mobile_urls', 'ad_group_ad.ad.responsive_search_ad.headlines', 'ad_group_ad.ad.responsive_search_ad.descriptions', 'ad_group_ad.ad.responsive_search_ad.path1', 'ad_group_ad.ad.responsive_search_ad.path2', 'ad_group_ad.ad.expanded_text_ad.headline_part1', 'ad_group_ad.ad.expanded_text_ad.headline_part2', 'ad_group_ad.ad.expanded_text_ad.description', 'ad_group_ad.ad.image_ad.image_url', 'ad_group_ad.ad.video_ad.video_url'],
    requiredFields: ['campaign.id', 'campaign.status', 'ad_group.id'],
    supportsSegmentsDate: true,
    supportsMetrics: true,
  },
  {
    name: 'ad_group_ad_asset_view',
    category: 'ad',
    description: 'Per-asset performance within RSA and other ad types',
    fields: ['ad_group_ad_asset_view.field_type', 'ad_group_ad_asset_view.performance_label', 'ad_group_ad_asset_view.asset', 'ad_group_ad_asset_view.enabled'],
    requiredFields: ['ad_group_ad_asset_view.field_type'],
    supportsSegmentsDate: true,
    supportsMetrics: true,
  },
  {
    name: 'campaign_search_term_view',
    category: 'search_term',
    description: 'Actual search query reports at campaign level',
    fields: ['campaign_search_term_view.search_term', 'campaign.id', 'campaign.name', 'campaign.status', 'segments.search_term_match_source', 'segments.search_term_targeting_status'],
    requiredFields: ['campaign.id', 'campaign_search_term_view.search_term'],
    supportsSegmentsDate: true,
    supportsMetrics: true,
    notes: 'CRITICAL: Always include campaign_search_term_view.search_term',
  },
  {
    name: 'search_term_view',
    category: 'search_term',
    description: 'Actual search query reports at ad group level',
    fields: ['search_term_view.search_term', 'search_term_view.ad_group', 'search_term_view.status', 'segments.search_term_match_source'],
    requiredFields: ['search_term_view.search_term'],
    supportsSegmentsDate: true,
    supportsMetrics: true,
  },
  {
    name: 'geographic_view',
    category: 'geographic',
    description: 'Performance by geographic location',
    fields: ['geographic_view.country_criterion_id', 'geographic_view.location_type', 'campaign.id', 'campaign.name', 'campaign.status'],
    requiredFields: ['campaign.id', 'campaign.status'],
    supportsSegmentsDate: true,
    supportsMetrics: true,
  },
  {
    name: 'user_location_view',
    category: 'geographic',
    description: 'Performance by user location',
    fields: ['user_location_view.country_criterion_id', 'user_location_view.region_criterion_id', 'user_location_view.targeting_location'],
    requiredFields: ['user_location_view.country_criterion_id'],
    supportsSegmentsDate: true,
    supportsMetrics: true,
  },
  {
    name: 'asset',
    category: 'asset',
    description: 'Asset details (images, videos, text, sitelinks, etc.)',
    fields: ['asset.id', 'asset.name', 'asset.type', 'asset.image_asset.full_size.url', 'asset.image_asset.full_size.width_pixels', 'asset.image_asset.full_size.height_pixels', 'asset.video_asset.youtube_video_id', 'asset.video_asset.youtube_video_title', 'asset.text_asset.text', 'asset.sitelink_asset.link_text', 'asset.sitelink_asset.description1', 'asset.sitelink_asset.description2', 'asset.callout_asset.callout_text', 'asset.structured_snippet_asset.header', 'asset.structured_snippet_asset.values', 'asset.lead_form_asset.business_name', 'asset.lead_form_asset.headline', 'asset.lead_form_asset.description', 'asset.promotion_asset.promotion_target', 'asset.price_asset.type', 'asset.final_urls'],
    requiredFields: ['asset.id', 'asset.type'],
    supportsSegmentsDate: false,
    supportsMetrics: false,
    notes: 'Snapshot resource - use for asset inventory',
  },
  {
    name: 'campaign_asset',
    category: 'asset',
    description: 'Assets linked to campaigns',
    fields: ['campaign_asset.asset', 'campaign_asset.field_type', 'campaign_asset.status', 'asset.type', 'asset.sitelink_asset.link_text', 'asset.final_urls', 'campaign.id', 'campaign.name', 'campaign.start_date', 'campaign.end_date'],
    requiredFields: ['campaign.id'],
    supportsSegmentsDate: false,
    supportsMetrics: false,
  },
  {
    name: 'asset_group',
    category: 'asset',
    description: 'Asset groups for Performance Max and Demand Gen',
    fields: ['asset_group.id', 'asset_group.name', 'asset_group.status', 'asset_group.final_urls', 'asset_group.final_mobile_urls', 'asset_group.path1', 'asset_group.path2', 'asset_group.ad_strength', 'campaign.id', 'campaign.name', 'customer.descriptive_name'],
    requiredFields: ['campaign.id', 'asset_group.id'],
    supportsSegmentsDate: true,
    supportsMetrics: true,
  },
  {
    name: 'asset_group_asset',
    category: 'asset',
    description: 'Per-asset performance in Performance Max asset groups',
    fields: ['asset_group_asset.asset', 'asset_group_asset.field_type', 'asset_group_asset.status', 'asset_group.id', 'asset_group.name'],
    requiredFields: ['asset_group.id'],
    supportsSegmentsDate: false,
    supportsMetrics: true,
  },
  {
    name: 'shopping_performance_view',
    category: 'shopping',
    description: 'Shopping campaign product-level performance',
    fields: ['segments.product_item_id', 'segments.product_title', 'segments.product_brand', 'segments.product_channel', 'segments.product_condition', 'segments.product_category_level1', 'segments.product_category_level2', 'segments.product_category_level3', 'segments.product_country', 'segments.product_language', 'segments.product_merchant_id', 'segments.product_store_id'],
    requiredFields: ['segments.product_item_id'],
    supportsSegmentsDate: true,
    supportsMetrics: true,
  },
  {
    name: 'product_group_view',
    category: 'shopping',
    description: 'Shopping listing group (product group) performance',
    fields: ['product_group_view.partition_type', 'product_group_view.product_group', 'campaign.id', 'campaign.name', 'campaign.status', 'ad_group.id', 'ad_group.name'],
    requiredFields: ['campaign.id'],
    supportsSegmentsDate: true,
    supportsMetrics: true,
  },
  {
    name: 'gender_view',
    category: 'demographic',
    description: 'Performance by gender',
    fields: ['gender_view.resource_name', 'ad_group_criterion.gender.type'],
    requiredFields: ['ad_group_criterion.gender.type'],
    supportsSegmentsDate: true,
    supportsMetrics: true,
  },
  {
    name: 'age_range_view',
    category: 'demographic',
    description: 'Performance by age range',
    fields: ['age_range_view.resource_name', 'ad_group_criterion.age_range.type'],
    requiredFields: ['ad_group_criterion.age_range.type'],
    supportsSegmentsDate: true,
    supportsMetrics: true,
  },
  {
    name: 'parental_status_view',
    category: 'demographic',
    description: 'Performance by parental status',
    fields: ['parental_status_view.resource_name', 'ad_group_criterion.parental_status.type'],
    requiredFields: ['ad_group_criterion.parental_status.type'],
    supportsSegmentsDate: true,
    supportsMetrics: true,
  },
  {
    name: 'audience',
    category: 'audience',
    description: 'Audience definitions',
    fields: ['audience.id', 'audience.name', 'audience.description', 'audience.status', 'audience.dimensions'],
    requiredFields: ['audience.id'],
    supportsSegmentsDate: false,
    supportsMetrics: false,
  },
  {
    name: 'change_event',
    category: 'change_history',
    description: 'Change history events (audit trail)',
    fields: ['change_event.change_date_time', 'change_event.change_resource_type', 'change_event.change_resource_name', 'change_event.changed_fields', 'change_event.client_type', 'change_event.user_email', 'change_event.old_resource', 'change_event.new_resource', 'change_event.resource_change_operation'],
    requiredFields: ['change_event.change_date_time'],
    supportsSegmentsDate: false,
    supportsMetrics: false,
    notes: 'CRITICAL: Use change_event.change_date_time for filtering, NOT segments.date. Must include LIMIT clause.',
  },
  {
    name: 'change_status',
    category: 'change_history',
    description: 'Change status of resources (added/changed/removed)',
    fields: ['change_status.last_change_date_time', 'change_status.resource_type', 'change_status.resource_status', 'change_status.resource_name'],
    requiredFields: ['change_status.last_change_date_time'],
    supportsSegmentsDate: false,
    supportsMetrics: false,
  },
  {
    name: 'conversion_action',
    category: 'conversion',
    description: 'Conversion action definitions',
    fields: ['conversion_action.id', 'conversion_action.name', 'conversion_action.status', 'conversion_action.type', 'conversion_action.category', 'conversion_action.value_settings.default_value', 'conversion_action.counting_type', 'conversion_action.attribution_model_settings.attribution_model'],
    requiredFields: ['conversion_action.id'],
    supportsSegmentsDate: false,
    supportsMetrics: false,
  },
  {
    name: 'label',
    category: 'label',
    description: 'Workspace labels',
    fields: ['label.id', 'label.name', 'label.status', 'label.text_label.background_color', 'label.text_label.description'],
    requiredFields: ['label.id'],
    supportsSegmentsDate: false,
    supportsMetrics: false,
  },
  {
    name: 'recommendation',
    category: 'recommendation',
    description: 'Google Ads recommendations',
    fields: ['recommendation.resource_name', 'recommendation.type', 'recommendation.impact.base_metrics.impressions', 'recommendation.impact.base_metrics.clicks', 'recommendation.impact.base_metrics.cost_micros'],
    requiredFields: ['recommendation.resource_name'],
    supportsSegmentsDate: false,
    supportsMetrics: false,
  },
  {
    name: 'customer',
    category: 'account',
    description: 'Account/customer-level information',
    fields: ['customer.id', 'customer.descriptive_name', 'customer.currency_code', 'customer.time_zone', 'customer.optimization_score', 'customer.auto_tagging_enabled'],
    requiredFields: ['customer.id'],
    supportsSegmentsDate: true,
    supportsMetrics: true,
  },
]

export const RESOURCES_BY_CATEGORY: Record<string, GaqlResource[]> = GAQL_RESOURCES.reduce(
  (acc, r) => {
    if (!acc[r.category]) acc[r.category] = []
    acc[r.category].push(r)
    return acc
  },
  {} as Record<string, GaqlResource[]>,
)

export function getResourceByName(name: string): GaqlResource | undefined {
  return GAQL_RESOURCES.find((r) => r.name === name)
}
