import { GoogleIcon } from '@/components/icons'
import type { BlockConfig } from '@/blocks/types'
import type { GoogleAdsResponse } from '@/tools/google_ads/types'

// Google Ads accounts configuration
const GOOGLE_ADS_ACCOUNTS = {
  ami: { id: '7284380454', name: 'AMI' },
  heartland: { id: '4479015711', name: 'Heartland' },
  nhi: { id: '2998186794', name: 'NHI' },
  oic_culpeper: { id: '8226685899', name: 'OIC-Culpeper' },
  odc_al: { id: '1749359003', name: 'ODC-AL' },
  cpic: { id: '1757492986', name: 'CPIC' },
  idi_fl: { id: '1890773395', name: 'IDI-FL' },
  smi: { id: '9960845284', name: 'SMI' },
  holmdel_nj: { id: '3507263995', name: 'Holmdel-NJ' },
  ft_jesse: { id: '4443836419', name: 'Ft. Jesse' },
  ud: { id: '8270553905', name: 'UD' },
  wolf_river: { id: '6445143850', name: 'Wolf River' },
  phoenix_rehab: { id: '4723354550', name: 'Phoenix Rehab (NEW - WM Invoices)' },
  au_eventgroove_products: { id: '3365918329', name: 'AU - Eventgroove Products' },
  us_eventgroove_products: { id: '4687328820', name: 'US - Eventgroove Products' },
  ca_eventgroove_products: { id: '5197514377', name: 'CA - Eventgroove Products' },
  perforated_paper: { id: '8909188371', name: 'Perforated Paper' },
  uk_eventgroove_products: { id: '7662673578', name: 'UK - Eventgroove Products' },
  monster_transmission: { id: '2680354698', name: 'Monster Transmission' },
  careadvantage: { id: '9059182052', name: 'CareAdvantage' },
  capitalcitynurses: { id: '8395621144', name: 'CapitalCityNurses.com' },
  silverlininghealthcare: { id: '4042307092', name: 'Silverlininghealthcare.com' },
  youngshc: { id: '3240333229', name: 'Youngshc.com' },
  nova_hhc: { id: '9279793056', name: 'Nova HHC' },
  inspire_aesthetics: { id: '1887900641', name: 'Inspire Aesthetics' },
  mosca_plastic_surgery: { id: '8687457378', name: 'Mosca Plastic Surgery' },
  marietta_plastic_surgery: { id: '6374556990', name: 'Marietta Plastic Surgery' },
  daniel_shapiro: { id: '7395576762', name: 'Daniel I. Shapiro, M.D., P.C.' },
  southern_coastal: { id: '2048733325', name: 'Southern Coastal' },
  plastic_surgery_center_hr: { id: '1105892184', name: 'Plastic Surgery Center of Hampton Roads' },
  epstein: { id: '1300586568', name: 'EPSTEIN' },
  covalent_metrology: { id: '3548685960', name: 'Covalent Metrology' },
  gentle_dental: { id: '2497090182', name: 'Gentle Dental' },
  great_hill_dental: { id: '6480839212', name: 'Great Hill Dental' },
  dynamic_dental: { id: '4734954125', name: 'Dynamic Dental' },
  great_lakes: { id: '9925296449', name: 'Great Lakes' },
  southern_ct_dental: { id: '7842729643', name: 'Southern Connecticut Dental Group' },
  dental_care_associates: { id: '2771541197', name: 'Dental Care Associates' },
  service_air_eastern_shore: { id: '8139983849', name: 'Service Air Eastern Shore' },
  chancey_reynolds: { id: '7098393346', name: 'Chancey & Reynolds' },
  howell_chase: { id: '1890712343', name: 'Howell Chase' },
}

export const GoogleAdsGoMarbleBlock: BlockConfig<GoogleAdsResponse> = {
  type: 'google_ads_go_marble',
  name: 'Google Ads (Go Marble)',
  description: 'Query Google Ads with direct GAQL - Python-style implementation',
  longDescription:
    'The Google Ads Go Marble block provides direct GAQL query execution without AI processing. This is a Python-equivalent implementation that mirrors the original Go Marble script functionality, offering raw access to Google Ads API with tools for running GAQL queries, listing accounts, and keyword planning.',
  docsLink: 'https://docs.sim.ai/tools/google-ads',
  category: 'tools',
  bgColor: '#34a853',
  icon: GoogleIcon,
  subBlocks: [
    {
      id: 'tool',
      title: 'Tool',
      type: 'dropdown',
      layout: 'full',
      options: [
        {
          label: 'Run GAQL Query',
          id: 'run_gaql',
        },
        {
          label: 'List Accounts',
          id: 'list_accounts',
        },
        {
          label: 'Keyword Planner',
          id: 'keyword_planner',
        },
      ],
      placeholder: 'Select tool...',
      required: true,
    },
    {
      id: 'customer_id',
      title: 'Customer ID',
      type: 'dropdown',
      layout: 'full',
      options: Object.entries(GOOGLE_ADS_ACCOUNTS).map(([key, account]) => ({
        label: account.name,
        id: key,
      })),
      placeholder: 'Select account...',
      required: false,
      condition: {
        field: 'tool',
        value: ['run_gaql', 'keyword_planner'],
      },
    },
    {
      id: 'query',
      title: 'GAQL Query',
      type: 'long-input',
      layout: 'full',
      placeholder: 'SELECT campaign.id, campaign.name, metrics.clicks FROM campaign WHERE segments.date DURING LAST_30_DAYS',
      rows: 4,
      required: false,
      condition: {
        field: 'tool',
        value: 'run_gaql',
      },
    },
    {
      id: 'manager_id',
      title: 'Manager ID (Optional)',
      type: 'short-input',
      layout: 'full',
      placeholder: '4455285084',
      required: false,
    },
    {
      id: 'keywords',
      title: 'Keywords (comma-separated)',
      type: 'short-input',
      layout: 'full',
      placeholder: 'hvac repair, air conditioning service',
      required: false,
      condition: {
        field: 'tool',
        value: 'keyword_planner',
      },
    },
    {
      id: 'page_url',
      title: 'Page URL',
      type: 'short-input',
      layout: 'full',
      placeholder: 'https://example.com',
      required: false,
      condition: {
        field: 'tool',
        value: 'keyword_planner',
      },
    },
  ],
  tools: {
    access: ['google_ads_go_marble'],
    config: {
      tool: () => 'google_ads_go_marble',
      params: (params) => ({
        tool: params.tool,
        customer_id: params.customer_id,
        query: params.query,
        manager_id: params.manager_id,
        keywords: params.keywords ? params.keywords.split(',').map((k: string) => k.trim()) : [],
        page_url: params.page_url,
      }),
    },
  },
  inputs: {
    tool: { type: 'string', description: 'Tool to execute: run_gaql, list_accounts, or keyword_planner' },
    customer_id: { type: 'string', description: 'Google Ads customer ID' },
    query: { type: 'string', description: 'GAQL query string' },
    manager_id: { type: 'string', description: 'Manager account ID (optional)' },
    keywords: { type: 'string', description: 'Comma-separated keywords for keyword planner' },
    page_url: { type: 'string', description: 'Page URL for keyword planner' },
  },
  outputs: {
    results: { type: 'json', description: 'Query results or account list' },
    totalRows: { type: 'number', description: 'Number of rows returned' },
    fieldMask: { type: 'string', description: 'Fields included in response' },
  },
}
